### ISSUE TITLE
Challenge does not show completion bar when expanded in list

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette3#101]
I have one challenge here that does not show a completion bar when expanded in the challenge list:

<img width="476" alt="screenshot 2018-02-12 11 09 53" src="https://user-images.githubusercontent.com/120452/36112000-589b966e-0fe5-11e8-8b05-0f4fa2310b53.png">

The challenge is http://maproulette.org/mr3/challenge/983

**Comment by mvexel** [comment]
Odd, when I tried again just now, it showed up. Might this have to do with the challenge having a large number of tasks, and the API request not returning in time?

<img width="474" alt="screenshot 2018-02-12 11 14 21" src="https://user-images.githubusercontent.com/120452/36112167-018fd91a-0fe6-11e8-8b3a-3b7eaaf61815.png">

**Comment by nrotstan** [comment]
It's likely that it just took a little while to load given the large number of tasks, but I'll investigate. We should add a busy indicator if that's the case.

**Comment by mvexel** [comment]
I think I will close this as I haven't observed this lately.
