### ISSUE TITLE
Create a path back after clicking on a task in the map 

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette3#102]
When the user clicks on a task in the map, they are immediately taken to the task view. From there, no path back exists to the previous state.

The optimal solution would be to have every state in the challenge list view be a permalink.

Another solution would be to add a confirmation 'Edit this task?' on marker click.

**Comment by nrotstan** [comment]
In alpha.4., the challenge name can now be clicked to go back to browsing the challenge (the browser back button should also work).
