### ISSUE TITLE
Challenge is not visible even though it's set to show

### ISSUE THREAD

**Issue by cliffordsnow** [maproulette/maproulette3#106]
My challenge is #2871  - at least I get to it by going to http://maproulette.org/map/2871

It was partially created in MR3 which many have caused part of the problem, although thats only a guess.

**Comment by mvexel** [comment]
Confirming that both @cliffordsnow 's project and the challenge are marked as 'visible'.

**Comment by mvexel** [comment]
The bug reported in #185 pops up for me here now too: If I follow the link in the ticket, I get taken to a different challenge.

**Comment by mgcuthbert** [comment]
As a note, the link provided is a MR2 UI link, and not related to MR3. The bug was on the backend, it has been fixed and the update will be deployed relatively soon. I am closing this as a duplicate as there is an issue #385 in maproulette2 project that references this exact issue.
