### ISSUE TITLE
Deleting a Challenge

### ISSUE THREAD

**Issue by jharpster** [maproulette/maproulette3#108]
When deleting a challenge the spinner just spins and spins endlessly and never returns. The challenge does appear to be successfully deleted eventually but not user facing message is surfaced.

**Comment by nrotstan** [comment]
Deleting a challenge can take multiple minutes if it has a lot of tasks, so I think that's what you're likely experiencing. We need to improve the user experience to take this into account.

**Comment by nrotstan** [comment]
The MR server now supports asynchronous deletes, and I've integrated support for that. I think that'll solve the UX issues.
