### ISSUE TITLE
Adopt Code of Conduct

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette3#1359]
OpenStreetMap US recently adopted a Code of Conduct which can be found [here](https://wiki.openstreetmap.org/wiki/Foundation/Local_Chapters/United_States/Code_of_Conduct_Committee/OSM_US_Code_of_Conduct). Let's adopt this same Code of Conduct for MapRoulette. It would apply to interactions here on Github (issues) as well as interactions within the application.

Next steps if this sounds like a good idea:

- [x] Ask OSM US if there are any conditions for usage
- [x] email coc@openstreetmap.us to opt in

**Comment by mvexel** [comment]
After talking to Maggie -- the process is a bit different. We need to get in touch with the CoC committee at coc@openstreetmap.us and let them know we plan to adopt OSM US CoC. Then they would handle any CoC violations that come up. We would need to link to the CoC in the application as well as on GitHub.

**Comment by mvexel** [comment]
Emailed the committee, awaiting response

**Comment by mvexel** [comment]
Agreed on doing the following to officially adopt the OSM US CoC:

- [] We add a notice to the GitHub front page for the project: https://github.com/osmlab/maproulette3 saying that folks who interact with each other through the MapRoulette platform (be it on the MapRoulette web site, social media or on Github, are bound by the OSM US CoC (with a link) 

- [] We add a notice to MapRoulette.org that notifies users of the same the first / next time they log in.

**Comment by danieldegroot2** [comment]
@mvexel Could you edit the first post with these to-do actions and add the `meta` and `needs documentation` labels to this issue?
This will make it easier to track the to-do actions.

**Comment by mvexel** [comment]
With the signing of the Charter Project agreement, we are bound to the OSM US CoC. We should make this clear on all surfaces where users can interact (here, maproulette.org, ...others?)
