### ISSUE TITLE
"Fix" button messaging a little ambiguous 

### ISSUE THREAD

**Issue by mgcuthbert** [maproulette/maproulette3#140]
The "Fix" button for a task is slightly ambiguous. Although technically correct, there could be an implication that you are setting the status of the current Task to "Fixed", where as something like "Edit" probably is a little clearer. It also would line up more with the terminology of the drop down when you click on "Fix" which then has "Edit in iD", "Edit in JOSM" and "Edit in new JOSM Layer".

So I think "Edit" would be a little clearer.

**Comment by nrotstan** [comment]
I've set it back to Edit for now. Maybe we can think about different language.
