### ISSUE TITLE
make https://maproulette.org/leaderboard less crushingly negative

### ISSUE THREAD

**Issue by matkoniecz** [maproulette/maproulette3#1566]
Typical mapper on opening https://maproulette.org/leaderboard will see:

3 people with ridiculous amount of points (including one apparently achieved without mapping? - #858)

7 more people with massive amount of points (100 000+)

Yourself, with people around you.

-------------

Maybe change order and show "you and neighbors that can be overtaken with a bit of mapping" can be displayed first?

**Comment by govvin** [comment]
I support this idea. I think there's a place for "leader boards" (project managers may like that), but also a place to show tasks that can inspire or challenge (potential) contributors to help out.

**Comment by mvexel** [comment]
We decided to make the default view the current month instead of "all time".

@CollinBeczak is working on implementing this, when it's done he can close the issue.

**Comment by CollinBeczak** [comment]
Resolved by this pr: https://github.com/maproulette/maproulette3/pull/2258
