### ISSUE TITLE
Once you have a large number of notifications, it is impossible to delete them

### ISSUE THREAD

**Issue by Noki** [maproulette/maproulette3#1569]
I collected a couple of thousand notifications and tried to delete them. The application tries to stuff all ids into a get URL which does not work. I can't even delete five of them because the logic takes all known ids instead of the 5 I selected:

![image](https://user-images.githubusercontent.com/198902/108606163-bbfc8f80-73b8-11eb-8f7a-7ca49947609c.png)

Expected behaviour: Be able to delete selected notifications. Maybe even have a "Delete all" option that works without IDs.

**Comment by danieldegroot2** [comment]
@mvexel This is a possible candidate for [inbox / messaging overhaul](https://github.com/osmlab/maproulette3/projects/14).
