### ISSUE TITLE
maproulette.org site unavailable via IPv6

### ISSUE THREAD

**Issue by bekreyev** [maproulette/maproulette3#1578]
maproulette.org have no AAAA DNS records and not unavailable via IPv6.

Please, enable IPv6 on the maproulette.org, analytics.maproulette.org and other resources of MapRoulette.

**Comment by mvexel** [comment]
I'll look into it, something I never thought about.. I also don't know much about it. Any guidance?

**Comment by bekreyev** [comment]
> I'll look into it, something I never thought about.. I also don't know much about it. Any guidance?

I think this guide can help with IPv6 at DigitalOcean:
https://www.digitalocean.com/docs/networking/ipv6/how-to/enable/
