### ISSUE TITLE
Shortcuts are not working when the 'buttons' are not displayed

### ISSUE THREAD

**Issue by Binnette** [maproulette/maproulette3#1595]
Hi Maproulette developers ❤️

Here is a simple bug. In the following screen I want to press shorcut 'f' for 'I fixed it' or even 'x' for 'Already fixed'. But those shortcut are not working.
![image](https://user-images.githubusercontent.com/6597721/114279299-2a161800-9a34-11eb-8f2f-99ca43946ea0.png)

... But if I click on the "Other..." button, then new shorcuts appears 😅 And now I can press 'f' or 'x'.
![image](https://user-images.githubusercontent.com/6597721/114279340-621d5b00-9a34-11eb-8f39-1fa93b02c0b0.png)

The bug fix is pretty simple, make shortcuts 'available' even is I don't click with my mouse on the button 'Other...'. Hum... simply because this is the main purpose of keyboard shortcut... to get rid of mouse clicking 🤣 😇

Thank a lot for fixing this bug ❤️

**Comment by jschwarz2030** [comment]
Thanks for reporting and good find!

**Comment by CollinBeczak** [comment]
We are looking into implementing this feature, initially we created a fix for this particular issue, but we will be expanding this to adjust to all edit buttons (not just the one in the task completion modal) and reconfigure the shortcuts to better interact with rapid. Linked: https://github.com/maproulette/maproulette3/issues/2127
