### ISSUE TITLE
Proposed OSM Tag Changes don't load normally when inspecting tasks.

### ISSUE THREAD

**Issue by atiannicelli** [maproulette/maproulette3#1596]
When inspecting tasks for my challenge I noticed that the first time that a task is loaded the proposed changes are not displayed properly. If I go back to the previous task and then forward to the task again then they are loaded properly. I made a video of what I'm talking about. You will see a task that looks good. Then I click on "next Task" and the task is loaded but proposed changes don't look correct. I then click "previous task" and then "next task" again and this time the proposed changes got loaded correctly.

I'm using Chrome on a Mac.

https://user-images.githubusercontent.com/5851115/114396770-efaf9680-9b6b-11eb-97ff-941c1af4d92e.mov

**Comment by jschwarz2030** [comment]
Thanks for posting this!  I will investigate.
