### ISSUE TITLE
Add OSMCha link to history panel

### ISSUE THREAD

**Issue by jgscherber** [maproulette/maproulette3#1604]
In the OSM History panel, it'd be nice if each changeset had a link to OSMCha for that changeset. The motivation would be that it'd make it easier to verify when marking the task as "already completed".

![image](https://user-images.githubusercontent.com/6207661/117363276-fc30c180-ae81-11eb-956d-feaaf9ae7294.png)

**Comment by mvexel** [comment]
Makes sense to do this. We'll also add an Achavi link.

**Comment by mvexel** [comment]
2023: let's forget about Achavi link
