### ISSUE TITLE
Custom base layer does not get picked up

### ISSUE THREAD

**Issue by tpikonen** [maproulette/maproulette3#1610]
When working on a simple task like moving a point according to imagery, it would be nice to have the iD editor start with the best (marked with a star in iD) background imagery available for the current region. The default background (e.g. Bing) is often slightly misaligned or not as sharp.

Alternatively, it should be possible for the challenge creator to assign a default background, but the best imagery for a region is often local (i.e. only covers a single country or other region), so it would probably mean that maproulette would need to know about all the available backgrounds in iD.

**Comment by mvexel** [comment]
The only way to communicate between MapRoulette and iD is through the URL parameters we pass. Do you know if there is a parameter you can pass to iD to tell it to show that 'best available' imagery?

**Comment by tpikonen** [comment]
Indeed there is a 'background' parameter for iD, the first one in this list: https://github.com/openstreetmap/iD/blob/develop/API.md

The best solution for the problem described in this report would be to allow the challenge creator to define this background parameter for editors which support it, definitely at least for iD.

**Comment by mvexel** [comment]
Challenge owners [can already set the preferred background imagery](https://learn.maproulette.org/documentation/setting-basemap-for-challenge/) to use within MR itself, and this imagery parameter is passed on to JOSM and iD. This should do what you intend?

**Comment by tpikonen** [comment]
Thanks, this seems to be exactly the feature I need. But no luck: I want to set [this](https://josm.openstreetmap.de/wiki/Maps/Finland#MMLOrthophoto) layer as the background imagery for my challenge, but setting https://tiles.kartat.kapsi.fi/ortokuva/{z}/{x}/{y}.jpg as the custom basemap just gives me the OSMcarto map :(

**Comment by mvexel** [comment]
I can confirm that this is a valid layer in QGIS, and a test challenge I created with this XYZ layer does indeed not work as expected. Identifying as bug and assigning to @jschwarz2030

**Comment by jschwarz2030** [comment]
this ticket should have been closed with the associated PR.  closing.
