### ISSUE TITLE
Error when searching location: "Unable to render the map: u is not a function"

### ISSUE THREAD

**Issue by mnalis** [maproulette/maproulette3#1611]
When I zoom in a little on map at https://maproulette.org/ I am presented with little window saying `Zoom in to view tasks` giving me button `Near Me`, text field `Location` and button `Search`. When I type name of the city (like `Zagreb`) in `Location` field and click `Search` (or press `enter`) error window pops up saying:

```
Oops!
Unable to render the map: u is not a function. Attempting to fall back to default map layer.
```

After dismissing the error window, map is gone and I have to refresh the page to get maproulette to work again

I've tried both in `Firefox 78.10.0esr (64-bit)` and `Chromium Version 90.0.4430.212 (Developer Build) built on Debian 10.9, running on Debian 10.9 (64-bit)`, and error appears in both.

I would have expected the map to zoom in to specified city, instead of failing with an error.

**Comment by mnalis** [comment]
`Near Me` button in that windows, seems to work normally. 
Also, magnifying glass icon on the middle right part of the map (which says it searches Nominatim) works fine.

**Comment by CollinBeczak** [comment]
This appears to be fixed, im going to go ahead and close this ticket. If you run into this issue again, let me know if there is any more information you can provide for reproducing this bug.
