### ISSUE TITLE
Repeated notification for finished campaign

### ISSUE THREAD

**Issue by davidbaumann** [maproulette/maproulette3#1614]
I am not sure if this is the correct repository to post this issue.

I think the issue is following:

If you have worked on a campaign that has finished, the campaign gets new tasks added, and then finished again, you always get a notification.

So whenever I log in,  I get some notifications which are irrelevant.

**Comment by mvexel** [comment]
Got it. One solution would be to reset notifications for a challenge whenever it is finished. So you wouldn't get any more unless you complete another task after new tasks are added. Would that solve the issue for you?

**Comment by Strubbl** [comment]
I am having the same issue.

> One solution would be to reset notifications for a challenge whenever it is finished.

How can i reset notifications for a challenge? Where do i find this option?

**Comment by danieldegroot2** [comment]
@mvexel This is a possible candidate for [inbox / messaging overhaul](https://github.com/osmlab/maproulette3/projects/14).
