### ISSUE TITLE
External id can be edited during edit phase but does not change the data

### ISSUE THREAD

**Issue by tordans** [maproulette/maproulette3#1736]
**Step by step:**

1. create challenge with external geojson
2. forget to set the external id during create phase
3. ==> a random id is created
4. edit challenge
5. add external id, save
6. ==> nothing changes

[See also SlackUS](https://osmus.slack.com/archives/C1QN12RS7/p1651599179764369)
> are you trying to get this to convert during the "edit" phase?  if so that may need to be addressed in a ticket.  adding "kennz" during edit will not replace the ids

**Suggested changes:**

a. During edit phase, when external id is change, regenerate the tasks; ideally preserve task history during this regeneration.
b. _OR_ During edit phase, make the external id field readonly an inform via form-hint that this can only be used during creation phase which likely means to duplicate, recreate / delete the challenge
c. _AND_ Update the docs which do not clearly state, yet, that how this works during different phases (creation vs. edit)

**Comment by mvexel** [comment]
Or, alternatively, if a challenge is created without an external id, notify the user if they try to update the challenge *with* an external id, telling them this is not possible.

I'm open to either solution, but the one I propose is probably less work :)

I agree that the documentation (I assume you are referring to [this page](https://learn.maproulette.org/documentation/setting-external-task-identifiers/#content) could do with some clarification.

**Comment by mvexel** [comment]
Related: https://github.com/osmlab/maproulette3/issues/547

**Comment by CollinBeczak** [comment]
> a. During edit phase, when external id is change, regenerate the tasks; ideally preserve task history during this regeneration. 

After looking at this, i don't think this solution would be something we could do at the moment. If its possible it would require a massive overhaul of how we generate tasks and how we handle duplication.

> b. _OR_ During edit phase, make the external id field readonly an inform via form-hint that this can only be used during creation phase which likely means to duplicate, recreate / delete the challenge 
> Or, alternatively, if a challenge is created without an external id, notify the user if they try to update the challenge with an external id, telling them this is not possible.

Implementing both of these features seems like it would be the best approach.
