### ISSUE TITLE
When looking at one of your own challenges, add a 'manage' button

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette3#175]
If looking at one of your 'own' challenges in the list, add a button to go to the manage page for that challenge.

**Comment by nrotstan** [comment]
Is this a duplicate of #87, or is this intended to represent an additional spot in which you'd like to see a manage control?

**Comment by mvexel** [comment]
It isn't an exact duplicate, but I think having it in challenge browse mode makes more sense than having it when looking at a task. Closing #87
