### ISSUE TITLE
[question] why are tasks bundled together by other users offered as the same bundle for other users?

### ISSUE THREAD

**Issue by govvin** [maproulette/maproulette3#1799]
I'm wondering why I'm offered tasks bundled by other users as the same bundle? 

Sometimes, the bundled tasks don't make sense to me. And often I would end up unbundling them, and reviewing (and/or fix) the tasks or bundle them differently.

I often get these bundled tasks mark as "too hard", and sometimes, certain tasks in the bundle are fixable. If a bundled task is not fixed, is it a good to keep offering them as a bundle?

**Comment by mvexel** [comment]
I don't have an immediate answer for you. Let me discuss and get back to this.

**Comment by CollinBeczak** [comment]
I've been working pretty closely with the widget you are talking about. I am going to prevent bundles from being marked as too hard( Now labelled "can't complete" ), but you will be able to add tasks with the status "too hard" to a bundle. There will be a feature added to remove individual tasks from a bundle, and later on in a newer release we will add a feature to add individual tasks to a bundle. You can see more details here: https://github.com/maproulette/maproulette3/pull/2291

**Comment by govvin** [comment]
That sounds awesome @CollinBeczak ! Thank you for working on this, and I'm looking forward to trying them out soon.

> I've been working pretty closely with the widget you are talking about. I am going to prevent bundles from being marked as too hard( Now labelled "can't complete" ), but you will be able to add tasks with the status "too hard" to a bundle. There will be a feature added to remove individual tasks from a bundle, and later on in a newer release we will add a feature to add individual tasks to a bundle. You can see more details here: #2291
