### ISSUE TITLE
Allow users to read Overpass queries even in challenges they do not own

### ISSUE THREAD

**Issue by Binnette** [maproulette/maproulette3#1800]
Hello @mvexel,

Is it possible to add a button on all "overpass query challenge" to allow all users to have a look to the Overpass Query?

I don't think there is any "intellectual property" on the Overpass queries. Plus OSM is kind an "OpenSouce Community". So sharing is caring.

That way, users can reproduce challenges in their own place/country. Plus it can allow users to "clone" an archived project.

Have a nice day 😊

**Comment by mvexel** [comment]
I think that should not be an issue from a sharing perspective. We could add a 'reveal overpass query' button somewhere here: 
<img width="678" alt="image" src="https://user-images.githubusercontent.com/120452/186262370-7167020f-aa30-4cf2-8061-3298f31c62fb.png">

I don't consider this a top priority issue but we'll consider it for a future release. Thanks for suggesting.

**Comment by Binnette** [comment]
Hi @mvexel thank a lot. It is perfect like this 👍
I am not in a hurry... Right now, I am converting my challenges from Overpass to PyOsmium. And I run my py scripts against the 65Go of OSM planet data 🤣😁😁😁
