### ISSUE TITLE
Ability to modify slippy map size during Nearby Task Selection

### ISSUE THREAD

**Issue by aawiseman** [maproulette/maproulette3#1809]
Summary:
Having the ability to modify the slippy map size when selecting a nearby task would be a good quality of life enhancement. Currently, users cannot modify the map size. This can lead to loss of spatial context, and it can sometimes be difficult to navigate around the map with such a small window and figure out where you are or where the challenge is. 

An alternative could be making the slippy map wider, as well as the comment box for visual balance/usability.

Steps To Reproduce:
1. Resolve task
2. Select ‘Nearby’ Next Task
3. Attempt to adjust slippy map

![Screen Shot 2021-04-28 at 3 36 22 PM](https://user-images.githubusercontent.com/5025092/187560617-1ed02575-06fc-467d-8ecc-8f5bf5ba691e.png)

**Comment by CollinBeczak** [comment]
This should have been closed with this PR: https://github.com/maproulette/maproulette3/pull/1854
