### ISSUE TITLE
No access to home project

### ISSUE THREAD

**Issue by hannushka** [maproulette/maproulette3#182]
I've just created a MapRoulette account but I can't seem to access my home project. When I try to add a edit my home project or add a new challenge I get 403 Error Page (Forbidden).

When I try to do the same at http://maproulette.org/mr3 I just get an error "can't save changes". Screenshot of error screen 
 
![screenshot from 2018-03-14 14-01-00](https://user-images.githubusercontent.com/9430712/37412530-608a0b3a-27a5-11e8-9f7d-88f57a85d307.png)

**Comment by mvexel** [comment]
Hi @hannushka -- thanks for reporting. 
From the screenshot it doesn't look like you're signed in?
What happens if you go to maproulette.org, click sign in, authorize access from OSM, then click on 'projects'?

**Comment by hannushka** [comment]
Hi @mvexel. Yes, it seems that I’m logged out from my account when I try to save edits to my project. Each time I log in, maproulette requests access to my OSM profile and when I accept, a new token is generated. Even though I’ve already granted the access before. In the list of tokens on my osm profile there are several tokens for “New MapRoulette”. 

When I go back to maproulette I’m signed in as usual. I’m only logged out when forwarded to this error screen after trying to save edits from the projects page.

**Comment by nrotstan** [comment]
I've been able to replicate this for new user accounts. Thank you for reporting!

**Comment by mgcuthbert** [comment]
This is now addressed in https://github.com/maproulette/maproulette2/pull/384.

**Comment by mgcuthbert** [comment]
Did not mean to close this issue, clicked on the wrong button. :)

**Comment by nrotstan** [comment]
This should now be fixed per maproulette/maproulette2#387
