### ISSUE TITLE
Make challenge link in changeset description mandatory

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette3#1823]
I would like to make it mandatory to have the link to the MapRoulette challenge in the changeset description.

Right now this is optional.

Ideally I would like #225 to be done first to minimize the payload, but I don't consider that as mandatory.

**Comment by SomeoneElseOSM** [comment]
Will it also be possible to view the person who created the maproulette thing without logging in to maproulette?

Strictly speaking, telling someone to do something via maproulette is an example of organised editing so that https://wiki.osmfoundation.org/wiki/Organised_Editing_Guidelines should be followed.  Some organisers do follow this (for example https://wiki.openstreetmap.org/wiki/Organised_Editing/Activities/Expedia , which is related to this issue).

Someone should be able to click through from an OpenStreetMap changeset to get to be able to message the person who "organised" it, which in this case is the OSM user who created the challenge, without having to log into an external system.

**Comment by mvexel** [comment]
> Strictly speaking, telling someone to do something via maproulette is an example of organised editing

This depends on the relationship between the organizer and those who make the edits, not on the tool used.

> Someone should be able to click through from an OpenStreetMap changeset to get to be able to message the person who "organised" it, which in this case is the OSM user who created the challenge, without having to log into an external system.

MapRoulette uses OSM OAuth for authentication so there is a 1:1 relationship between MapRoulette usernames and OSM ones. 

We display the name of the MapRoulette user with every Challenge even if you're not signed in: 

![image](https://user-images.githubusercontent.com/120452/192603131-17cd300a-4199-4081-b641-a858c87e775c.png)

With that information, you can message the user on OSM. 

Now, we can make it easier by adding a link to compose a new OSM message like we do on the Task screen:

![image](https://user-images.githubusercontent.com/120452/192603470-dbbad9b0-8adb-4d16-8f39-2d09e457936a.png)

Is that something you think would be helpful for those who really don't want to sign in to MapRoulette using their OSM account?

**Comment by mvexel** [comment]
A note unrelated to the comment above: I don't think there is a way to prevent mappers from modifying the changeset comment to remove the link, so this is not a guarantee that the link between a changeset and the MapRoulette challenge will exist on the OSM side, but I believe it's as close as we can reasonably get.

**Comment by mvexel** [comment]
See also #1899 for the issue raised above, following discussion [here](https://community.openstreetmap.org/t/maproulette-request-for-comments-liking-and-flagging-challenges/5838)

**Comment by mvexel** [comment]
What I stated above is not technically correct -- the default project created when a user first registers themselves with MapRoulette is called `[OSM user display name]'s Project` but a) this name can be changed and b) users can create additional projects with names that don't include their OSM user display name.

**Comment by mvexel** [comment]
Discussing with @jschwarz2030 this is how we will implement:

* MapRoulette Challenge link (if implemented, shortened #225) will always be included in the changeset comment if and only if the challenge is discoverable at the time the mapper works on the task
* There will be a server configuration flag to override this behavior but maproulette.org will not have this flag set.
* The switch in the Challenge wizard to enable / disable adding the URL to the changeset comment will be removed.

Note that mappers can still always edit the changeset comment before committing the edit to OSM, so there can never be a guarantee that the linkage between an OSM changeset and a MR task exists - unless we use [changeset tags](https://wiki.openstreetmap.org/wiki/Changeset#Tags_on_changesets) instead?
