### ISSUE TITLE
False case of «You have marked all remaining tasks in this challenge as either skipped or too hard.»

### ISSUE THREAD

**Issue by tuxayo** [maproulette/maproulette3#1826]
There are 1200 remaining tasks on this:
https://maproulette.org/challenge/14102

But when I start I get the same few tasks that I marked as too hard. And when I do "Next" or remark them as "Too hard" at best it cycles in the other few tasks and says «You have marked all remaining tasks in this challenge as either skipped or too hard.»

But if from the challenge page I zoom on the map to manually pick a task, I find valid tasks.

**Comment by tuxayo** [comment]
I suspect that the "other few tasks" (the ones which are only shown) all have medium priority. (checked on 2 of them) As opposed to low for the other tasks.

**Comment by CollinBeczak** [comment]
This ticket should have been resolved on the submission of this pull request: https://github.com/maproulette/maproulette-backend/pull/1110
