### ISSUE TITLE
Admin Metrics Dashboard

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette3#1837]
I would like to gain more at-a-glance insight into metrics about users, projects and challenges:

* A sortable list of all projects with core metrics (ID, number of challenges, number of total tasks, owner, number of users engaged with tasks, date created, date last modified, archived or not, and if possible a mini chart showing engagement over time)
* A sortable list of challenges with the same core metrics (except of course for the number of challenges :))
* A sortable list of users with date registered, date last active, total days active, number of challenges participated in, total tasks completed (by status)
* Clicking on a project or challenge will take you to the existing project / challenge admin page
* Clicking on a user will take you to their OSM user page
* Option to export each as CSV
* Tables should be sortable by each column.
* Nice to have would be a typeahead search to filter by name.
* This admin metrics section should show up in the top right dropdown menu but only for superusers.
* The list should be paginated (50 rows per "page"). Changing the sorting takes you back to "page 1"

**Comment by mvexel** [comment]
I would also love to include somehow a burndown chart of tasks in each project / challenge like we have in the Challenge management screen, example:

![image](https://user-images.githubusercontent.com/120452/195441160-e4447353-53dd-45c6-83b4-29538110765e.png)

**Comment by aawiseman** [comment]
One thing that might be useful is to be able to choose the time period for the metrics. For example the project page looks like this, but that's all time, but maybe you just want to see the last 6 months of stats, or last month, or whatever time period.

<img width="629" alt="Screen Shot 2022-10-13 at 10 24 30 AM" src="https://user-images.githubusercontent.com/5025092/195664634-3b8e2157-1e1f-40cc-afab-eb889ebdcc17.png">

**Comment by mvexel** [comment]
We need to consider discoverable vs private challenges. Users keep challenges private for a reason. If and when we make this dashboard publicly available we would need to have two views - a public view with just public projects and challenges, and a superuser view that exposes everything. We need to build this into the design from the start.

**Comment by mvexel** [comment]
Following up on this -- as discussed with @tsun812 @javtran -- the dashboard will initially only be usable by superusers, but will will build in a filter to show / hide non-discoverable challenges. If and when we are ready to release a version of this to all MR users, we can then use this filter to show a dashboard for the general public that hides non-discoverable challenges. 

Question for the future is how we filter more accurately to show to any user whatever challenges they have visibility on:

* Superuser - everything
* Challenge / Project owners - all public challenges and the challenges they own
* Everyone else - all public challenges.

**Comment by mvexel** [comment]
Two additional asks for this @tsun812 @javtran 

1. Narrow results using "from" and "to" date -- for example I want the table to reflect only data from 2022-01-01 until 2022-07-01
2. Show number of Challenge-level comments in the table

We can discuss when we meet on Monday
