### ISSUE TITLE
Translate documentation into other languages

### ISSUE THREAD

**Issue by aawiseman** [maproulette/maproulette3#1839]
I think it would be great to translate the documentation, at least some of it, into different languages. For example, I got a question from the Mexico OSM community for how to use it and create their own challenges, but my Spanish is probably not good enough to do a tutorial.  

To start I think these pages would be the most useful 

- Discovering challenges https://learn.maproulette.org/documentation/discovering-challenges/
- Creating a challenge https://www.openstreetmap.org/user/mvexel/diary/46863
- Using Overpass to create a challenge https://learn.maproulette.org/documentation/using-overpass-to-create-challenges/

**Comment by mvexel** [comment]
@ryanscherler is looking into ways to support multiple languages in the platform we currently use for learn.maproulette.org. But whatever the outcome of that, I love this idea. At its most basic, we can just add a section for other languages and add a link to the English language page to point to any other languages available.

**Comment by mvexel** [comment]
There is now a transifex setup for translating docs!
