### ISSUE TITLE
Own OAuth token for each sign-in

### ISSUE THREAD

**Issue by wolfgang-8** [maproulette/maproulette3#1847]
Each time I sign-in, MapRoulette request access to my OSM account and create a new token in the "OAuth 1 settings". So, there are many "New MapRoulette" tokens in the OAuth list. This also happens within the same browser session, if I sign-in and sign-out frequently. Can this behavior be changed?

**Comment by mvexel** [comment]
Once you sign out or clear your browser cookies, the MapRoulette OAuth access token is deleted, so I don't think there is a way to re-use it without compromising security. I may be wrong here @jschwarz2030 ?

**Comment by jschwarz2030** [comment]
@ljdelight and I have discussed this in the past.  We do store the oauth token in the user table and there may be a way to indicate to OSM that we already have a token and just need to know who the user is.  We still have to redirect to OSM no matter what.

Additionally, and probably a separate discussion, is migrating to oauth2 at some point.  Maybe this would naturally improve things but probably a larger effort.

**Comment by mvexel** [comment]
I created #1876 to cover the OAuth migration

**Comment by mvexel** [comment]
Closing this in favor of #1876
