### ISSUE TITLE
browse/challenge/:id page should not present user with a "Please sign in" modal

### ISSUE THREAD

**Issue by jschwarz2030** [maproulette/maproulette3#1862]
The challenge browse page should not present the user with an error if they're not signed in.  It should behave similarly to the Find Challenges and Leaderboard pages, allowing the user to explore but sign in if they choose to participate.

<img width="1498" alt="Screen Shot 2022-11-17 at 12 02 07 PM" src="https://user-images.githubusercontent.com/79289630/202522784-a62d409f-79aa-4a16-b689-e4047997b9fc.png">

**Comment by SomeoneElseOSM** [comment]
I don't believe that this is actually resolved, at least not on https://maproulette.org .

Currently I've followed a link from https://community.openstreetmap.org/t/overturemaps-org-big-businesses-osmf-alternative/6760/180 to https://maproulette.org/browse/challenges/8113 , and there appears to be no information of note at https://maproulette.org/browse/challenges/8113 .  If I click through to https://maproulette.org/browse/projects/4187 (it's not obvious in the UI that that is even a link, but I know from being told in bugs such as this that it is) I can't get back to https://maproulette.org/browse/challenges/8113 , only to some other "challenges".  I can't see who did what to what.
