### ISSUE TITLE
Migrate to OAuth 2

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette3#1876]
OSM now supports OAuth 2. There is no deprecation path for the legacy 1.0a support, but we should prepare to migrate our authentication to the new standard.

**Comment by mvexel** [comment]
@bhousel ^^^

**Comment by mvexel** [comment]
There's currently no official signals *yet* from the OSM side about if / when OAuth 1.0a is going to be deprecated but I would prefer us be prepared. Implementing this may also resolve #1847 .

**Comment by mmd-osm** [comment]
Respective upstream issue on OSM operations tracker: https://github.com/openstreetmap/operations/issues/867
