### ISSUE TITLE
GeoJson not loading

### ISSUE THREAD

**Issue by baditaflorin** [maproulette/maproulette3#188]
Attached different files here 
[MAPROULETTE.zip](https://github.com/maproulette/maproulette3/files/1815750/MAPROULETTE.zip)

**Comment by nrotstan** [comment]
Thanks for reporting @baditaflorin, I tried the first file in the zip (terrant-named-links_osm_id.geojson) and was able to create a challenge with it (and tasks were built). Can you elaborate a bit more on the specific issue you're encountering?

**Comment by nrotstan** [comment]
After some additional experimentation, I think this could be related to #222, which will have a fix included in the beta.4 release.
