### ISSUE TITLE
Challenge title gets cut off at comma in recent activity overview

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette3#1882]
See the screenshots below

![SCR-20221202-ibm](https://user-images.githubusercontent.com/120452/205377646-9891a188-3894-48d8-9d22-d0746872a039.png)
![SCR-20221202-ibf](https://user-images.githubusercontent.com/120452/205377650-416aa36b-bb28-4f25-bab8-aef73ed26150.png)

**Comment by caroline223** [comment]
<img width="1024" alt="Screen Shot 2023-02-23 at 10 47 02 PM" src="https://user-images.githubusercontent.com/67647836/221087162-ba14a0de-b8aa-407b-b4be-8f166facbf18.png">
@mvexel As you can see in the screen shot, I created several different challenges with different challenge titles that includes other special characters along with commas to see if the challenge title gets cut off after any special character or just commas. Based on my testing, it appears that the title simply cuts off after a comma. Do you thing this would be a RegEx issue?
