### ISSUE TITLE
I want to add italian language

### ISSUE THREAD

**Issue by loviuz** [maproulette/maproulette3#1884]
Hi,
can I translate maproulette in italian? I have checked transifex but there is non italian language.

Thanks in advance!

**Comment by mvexel** [comment]
I just accepted the request to add Italian to the MapRoulette transifex project: https://www.transifex.com/osmlab/maproulette3/language/it_IT/

**Comment by mvexel** [comment]
And thanks for offering to translate!

**Comment by loviuz** [comment]
Hi, when will you plan to release italian translation? We have translated all strings about 2 month ago :-)

**Comment by jschwarz2030** [comment]
Apologies.  I didn't update our transifex files in the last deployment.  i'll get this patched by next week.
