### ISSUE TITLE
Unsubscribe from notifications about past challenges

### ISSUE THREAD

**Issue by hfs** [maproulette/maproulette3#1885]
I once took part in the challenge `France | Polygon has self intersection`. It was finished and I got a notification about it. Yay!

But now the error detection process is run repeatedly and if new issues are found the old challenge is re-activated. Then it gets finished again the same or next day and I get another notification.

There are some past challenges where I get almost daily notifications.

![Screenshot of personal notification inbox on MapRoulette](https://user-images.githubusercontent.com/538109/205497398-1d5bf579-8f0c-4730-b89c-7bd806f0ea39.png)

It would be nice if there was an option to unsubscribe from notifications about a challenge. It could e.g. be displayed at the bottom of the notification message. “Unsubscribe from notifications about this challenge” or something like that.

**Comment by mvexel** [comment]
Sorry for that. This was noted by a few users (see for example also #1614) and we're working on this.
I'll close this one and keep #1614 open.
