### ISSUE TITLE
Make it easier to discover the OSM username for the Challenge owner on the Browse page

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette3#1899]
The OSM username should be immediately visible. Need to decide if we want this to be a link to send a new message through OSM to that user.

**Comment by SomeoneElseOSM** [comment]
See also https://lists.openstreetmap.org/pipermail/talk-gb/2023-February/030003.html and https://community.openstreetmap.org/t/how-to-contact-the-person-group-running-a-maproulette-challenge/2705/30 .

**Comment by mvexel** [comment]
Let's put this underneath "Task Data Sourced"

**Comment by matkoniecz** [comment]
https://community.openstreetmap.org/t/how-to-contact-the-person-group-running-a-maproulette-challenge/2705/32 describes it as not actually fixed
