### ISSUE TITLE
Allow to remember "show nearby" by default

### ISSUE THREAD

**Issue by matkoniecz** [maproulette/maproulette3#1905]
I am not heavy MR user, but in general I strongly "show nearby" rather jumping across country or world - I prefer to edit area known to me.

Sadly "random" is set by default and I often forget to switch it what is annoying to recover from

I checked https://maproulette.org/user/profile

Maybe even set it as default for all? It seems that if user selected specific tasks that they are likely to be interested in given area and solving multiple tasks in one are is preferable as it gives more context to mapper and makes monitoring changes for others more effective.

**Comment by mvexel** [comment]
We can consider introducing a user setting to "remember" this. I'll add it to enhancements we're considering.
