### ISSUE TITLE
Creating a challenge using a line-by-line file does not work

### ISSUE THREAD

**Issue by KristjanESPERANTO** [maproulette/maproulette3#1914]
I'm trying to create a challenge by using a line-by-line GeoJSON file. Unfortunately, the spinner runs forever during the import and there is no result. Even if I take the [simple example from the documentation](https://learn.maproulette.org/documentation/line-by-line-geojson/) with three entries, this happens.

Here is the file I am using: [test.txt](https://github.com/maproulette/maproulette3/files/10299787/test.txt)

Am I doing something wrong?

**Comment by jschwarz2030** [comment]
Remove the `<RS>` from each entry.  I tested your file after modifying it and it works.

The documentation could probably use some clarification.  The `<RS>` just implies you should include a record separator, but as a text or json file, that's automatically provided when it's on a new line.

**Comment by KristjanESPERANTO** [comment]
Okay, I was mainly looking at the example and not reading the text carefully. I can now import nodes. Thanks! :smiley:
