### ISSUE TITLE
RapiD / iD integration

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette3#1922]
HOT TM has direct integration with the iD editor. On the task screen, you see the task instructions on the right, and a "framed" version of the iD editor on the left in the same window. This reduces context switching and makes for a smoother user experience.

![image](https://user-images.githubusercontent.com/120452/210629134-392bef44-ab89-4a52-920d-1c0811199932.png)

I would like to consider doing this for MapRoulette as well. I understand that this is not a quick fix; there will be broader implications for the UI and UX that need careful consideration. I am opening this ticket to discuss. This could be a candidate for the 2023 roadmap.

**Comment by mvexel** [comment]
Tagging some relevant issues and PRs on the HOT TM and iD sides:

* https://github.com/hotosm/tasking-manager/issues/1358
* https://github.com/openstreetmap/iD/issues/5856

Tagging some folks who have been involved in this: @bhousel @willemarcel @quincylvania @xamanu

**Comment by matkoniecz** [comment]
Some limitations are: worse handling on smaller screens (based on screenshot provided), things will likely get worse for people editing in JOSM.

**Comment by mvexel** [comment]
The smaller screen issue is something to consider, a user setting could be to disable the internal editor.

**Comment by mvexel** [comment]
Current discussion document: https://docs.google.com/document/d/1mAWlkRt_IKVc6SvR-XvM7GbStrthzE2WX02q1UZj6cY/edit#heading=h.5r01piigr50x

**Comment by mvexel** [comment]
Things to think about:

* limiting editor capabilities
* retaining Rapid settings

**Comment by mvexel** [comment]
* need to think about the UX implications regarding button layout future mobile supprt
