### ISSUE TITLE
Challenge comments not shown or linked in Create & Manage view

### ISSUE THREAD

**Issue by matkoniecz** [maproulette/maproulette3#1928]
I was looking through https://maproulette.org/admin/project/50406/challenge/37205?filters.metaReviewStatus=0%2C1%2C2%2C3%2C5%2C6%2C7%2C-2&filters.priorities=0%2C1%2C2&filters.reviewStatus=0%2C1%2C2%2C3%2C4%2C5%2C6%2C7%2C-1&filters.status=0%2C1%2C2%2C3%2C4%2C5%2C6%2C9&boundingBox=-0.18127441406250003%2C50.55881484085449%2C6.174316406250001%2C51.93410531270822&includeTags=false&page=0&pageSize=20&sortCriteria.direction=DESC&sortCriteria.sortBy=name&zoom=8 as logged in author and was unable to find chat comments listed in https://maproulette.org/browse/challenges/37205?tab=conversation

Maybe there is a link but at least I failed to find it

**Comment by mvexel** [comment]
Currently the comments are only shown on the public-facing challenge page. It may be possible to add a widget to duplicate this information to the admin page. I don't see this as a high priority but if someone wants to implement it I'm happy to merge it. 

![image](https://user-images.githubusercontent.com/120452/211924066-22a126dc-1539-4b6c-9bd4-658e655f71f0.png)
