### ISSUE TITLE
502 errors

### ISSUE THREAD

**Issue by matkoniecz** [maproulette/maproulette3#1937]
after log in to https://www.maproulette.org/ I get

![screen02](https://user-images.githubusercontent.com/899988/213864233-d73c877f-60b8-4fa8-b4cd-186f4855611d.png)

```
# https://github.com/osmlab/maproulette-python-client
import maproulette
import json

api_key = None
with open('secret.json') as f:
    data = json.load(f)
    api_key = data['maproulette_api_key'] 
    # https://github.com/osmlab/maproulette-python-client#getting-started
    # Your API key is listed at the bottom of https://maproulette.org/user/profile page.
    # expected file structure:
    """
{
        "maproulette_api_key": "d88hfhffiigibberishffiojsdjios90su28923h3r2rr"
}
"""

config = maproulette.Configuration(api_key=api_key)
api = maproulette.Project(config)
my_project_name = "404"
print(json.dumps(api.find_project(my_project_name), indent=4, sort_keys=True))
```

this used to work, now gives me 502 errors

(should I report it here or on https://github.com/osmlab/maproulette-python-client ?)

**Comment by jschwarz2030** [comment]
I am seeing we had some performance issues for about 10 minutes.  Things seem normal now, but will track down the cause.  Can you try again and let me know if you're still encountering this?
