### ISSUE TITLE
Automatically "unfeature" challenge once completed

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette3#1948]
Featured challenges remain visible on the challenge discovery page even if they're finished.

When a challenge is finished (no more tasks remain that are "created" or "skipped") the "featured" flag should be removed.

**Comment by MattEspoz** [comment]
Hey @mvexel !

Just wanted to confirm that by 'featured flag should be removed' means that the featured challenge tag (in challenge detail page) should be removed when completed.


<img width="1137" alt="Screenshot 2023-03-02 at 3 30 10 PM" src="https://user-images.githubusercontent.com/70907264/222544918-fad86f2e-8c70-479f-8c37-cc3c11e7dfb7.png">

**Comment by mvexel** [comment]
Trying to reproduce this issue together with @jschwarz2030 and determined that 

a. I described the issue poorly and 
b. The first part of my statement (that a featured challenge remains visible in the discovery page even if completed) is not true.

So, closing this as `not an issue` with my apologies.
