### ISSUE TITLE
Allow spaces in urls in markdown fields

### ISSUE THREAD

**Issue by kubahaha** [maproulette/maproulette3#1950]
**Is your feature request related to a problem? Please describe.**
I'd like to link to some advanced Overpass query in each taks in "instructions" field. Overpass is calculated with some keys values which can have spaces.

**Describe the solution you'd like**
Id like to allow linking to websites like `[Overpass](https://overpass-turbo.eu?Q=Some example)`. Common approach is to enclose URL with diamond braces - eg. `[Overpass](<https://overpass-turbo.eu?Q=Some example>)`

**Describe alternatives you've considered**
It's not possible to automatically replace spaces by html code.

**Additional context**
I also don't know how is it possible to properly escape mustache tags, eg. in `{{geocodeArea:{{addr:city}}}}->.searchArea;` `{{geocodeArea` is also interpreted as mustache tag.

**Comment by mvexel** [comment]
I agree we should support this.

For the URLs with spaces: @jschwarz2030 does our markdown parser support the diamond brace convention that @kubahaha suggests? If so that sounds like the way to go if it doesn't break existing behavior.

For escaping mustache tags, could we escape those with backslashes?

**Comment by mvexel** [comment]
@kubahaha If you have a moment please let us know if the above solves your issue, if so we can close it :) Thanks!

**Comment by kubahaha** [comment]
@mvexel thanks for reminder.
I can confirm spaces in addresses works as expected, however mustache tag escaping is not working for me - probably because I try to use it in block code:

Following example (first 3 lines of my code) gets rendered wrong (assuming `addr:city=Mylin`):
```
‌‌ ```
[out:xml][timeout:999];
area[name="{{addr:city}}"]->.searchArea;
\{\{geocodeArea:{{addr:city}}\}\}->.searchArea;
```
_(for compatibility i inserted 2 extra chars before `` ``` `` in my code)_
![Screenshot at 00-06-40](https://user-images.githubusercontent.com/6720051/225163019-e110d16a-d792-4bd6-ba49-0e53673f33b3.png)
