### ISSUE TITLE
Clone someone else's challenge

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette3#1956]
**Is your feature request related to a problem? Please describe.**
Currently you can only clone a challenge you made (or made by someone in the same MR project as you). 

**Describe the solution you'd like**
Allow anyone to clone a challenge they see. The original challenge author can set a flag that would make the challenge clonable or not.

**Describe alternatives you've considered**
Sharing the overpass query kind of works, but the other person would still need to put in all the rest of the information.

**Additional context**
I have [this challenge](https://maproulette.org/browse/challenges/37917) and it would be nice if others could create this for their own city as well!

**Comment by jschwarz2030** [comment]
Where should the Clone button be accessible?  Public Challenge page?  Discoverability page?

**Comment by tsun812** [comment]
This is the UI flow in our mind.
- User goes to public challenge page to clone a challenge globally.
- A clone link will appear only if, challenge is cloneable and user is logged in and user has at least one project.
- After clicking clone link, a project modal will pop up for user to choose which project to put the challenge in.
- Upon completing project selection, user will be redirected to clone page to finalize on the challenge cloned.

**Comment by mvexel** [comment]
As discussed:

* We won't add the option for users to disable cloning their challenges
* We will limit cloning to discoverable challenges

What would be a fantastic bonus is if we could include the cloned challenge's overpass query but commented out. For example in the challenge linked above this is the original:

```
rel(198770);map_to_area->.a;
nw[amenity=restaurant](if(timestamp() < "2018-01-01T00:00:00Z"))(area.a);
out meta center;
```

What we would paste instead:

```
/*
THIS IS THE QUERY OF THE CHALLENGE YOU CLONED
PLEASE ADAPT BEFORE USING TO AVOID CREATING DUPLICATE TASKS
rel(198770);map_to_area->.a;
nw[amenity=restaurant](if(timestamp() < "2018-01-01T00:00:00Z"))(area.a);
out meta center;
*/
```

The `/*` /  `*/` is what Overpass uses for multi line comments.
