### ISSUE TITLE
Lack of tasks instruction

### ISSUE THREAD

**Issue by KatarzynaBW** [maproulette/maproulette3#1959]
Hello,

**Describe the bug**
I would like to create a Challenge in which the descriptions of tasks are different. 
I have used instructions on this page, but something is going wrong. 
Is it possible to point out a detailed instruction or a mistake I made when creating the geojson file? 

**Expected behavior**
Instruction per challenge should be visible.

**To Reproduce**
1. create the challenge - leave overall task instruction field empty
2. upload date accordingly
3. open the task after the challenge creation
4. Instruction per tasks is invisible

![image](https://user-images.githubusercontent.com/103265372/219684856-23c80785-a9b0-4c83-b661-1ac1fd1845c3.png)

Thanks in advance,
Kasia
Geojson:
{
"type": "FeatureCollection",
"name": "MR_tryout_2",
"features": [
{ "type": "Feature", "properties": { "osmid": "383085625", "country": "ESP", "comment": "Isolated Highway" }, "geometry": { "type": "MultiLineString", "coordinates": [ [ [ 0.7327447, 41.0417858 ], [ 0.7329061, 41.0416939 ] ] ] }, "instruction": "Remove data"},
{ "type": "Feature", "properties": { "osmid": "802494023", "country": "ESP", "comment": "Isolated Highway" }, "geometry": { "type": "MultiLineString", "coordinates": [ [ [ 1.0466684, 41.1821282 ], [ 1.0466845, 41.1821101 ], [ 1.0468166, 41.1821883 ] ], [ [ 1.0466239, 41.1821042 ], [ 1.0466684, 41.1821282 ] ], [ [ 1.0466684, 41.1821282 ], [ 1.0466085, 41.1821941 ] ] ] }, "instruction": "Fix inconsistencies" }
]
}

**Comment by CollinBeczak** [comment]
Where did the instructions property come from?
