### ISSUE TITLE
Request review by default

### ISSUE THREAD

**Issue by hdevine825** [maproulette/maproulette3#1964]
**Describe the solution you'd like**
I would like to enable review on all tasks within a challenge so that I can check work initially to refine instructions. It would be controllable within the settings of the challenge. 

**Additional context**
Adding an option so that the request review box is prechecked when a user completes a challenge but could uncheck to opt out. Alternatively, the checkbox could be invisible or non-interactive so review is requested without an option to opt out. Both could be options in challenge settings.

**Comment by adiatmad** [comment]
+1 on this idea. Some challenges on MapRoulette are used for disaster mapping response. Option reviews by default can help to maintain the data quality.  

https://maproulette.org/browse/projects/51027
