### ISSUE TITLE
Option to show tasks only in selected country

### ISSUE THREAD

**Issue by Filip10** [maproulette/maproulette3#1971]
Please add option to filter tasks by countries. Because I want to map only in my country, and I think some others too.

Thx, Filip.

**Comment by mvexel** [comment]
Can you describe how you envisage this feature working, @Filip10 ?

Possibly related  to #1797 / #1798

**Comment by Filip10** [comment]
On site browse challenges.
![obrázok](https://user-images.githubusercontent.com/25711588/223540024-b78612d9-650a-464b-a00e-323c52a4df90.png)
You somehow choose specific country. For instance I choose Slovakia.
![obrázok](https://user-images.githubusercontent.com/25711588/223540764-01675422-fb49-4689-98dc-40a5555a27ba.png)
Map will zoom to selected country and on left side show only task available in selected country.
Banner in the top could maybe be used for this.
And then you will see tasks only in country you selected.

And maybe somehow after clicking on challenge just filter tasks inside chosen country.

**Comment by atiannicelli** [comment]
I agree - this would be nice. It goes toward adding the ability to limit the area that you are interested in within a challenge. See: https://github.com/maproulette/maproulette3/issues/1797

**Comment by mvexel** [comment]
We will do:
* add lasso tool to the challenge screen map, which would work the same as the lasso on the challenge discovery page.
Realizing that this does not completely satisfy the request, this is much easier to implement at this point
