### ISSUE TITLE
Missing italian language

### ISSUE THREAD

**Issue by loviuz** [maproulette/maproulette3#1975]
**Describe the bug**
In MapRoulette 3.11.9 there is italian language, but in the web interface on https://maproulette.org, under User Settings, the italian language is not available.

**Expected behavior**
Italian language should be selectable.

**To Reproduce**
1. Log in
2. Go to User Settings
3. Check italian language in Locale

**Screenshots**
Screenshot is useful in this case.

**Desktop (please complete the following information):**
- Firefox 110.0.1 under Ubuntu 22.04

**Additional context**
None.

**Comment by Mte90** [comment]
![immagine](https://user-images.githubusercontent.com/403283/223376039-4b0c569e-7db3-452b-ba73-e411c95545f8.png)

The lang file is there https://github.com/maproulette/maproulette3/blob/develop/src/lang/it_IT.json

Also the language order in that list is not alphabetical 😅

**Comment by loviuz** [comment]
added here:
https://github.com/maproulette/maproulette3/pull/1978
