### ISSUE TITLE
Add a urlEncode filter to mustache tagging

### ISSUE THREAD

**Issue by Binnette** [maproulette/maproulette3#1986]
**Is your feature request related to a problem? Please describe.**

Here is my issue, I created a challenge (https://maproulette.org/admin/project/38938/challenge/38380) with this 'Detailed Instructions for Mappers':

`Use [nsi.guide](https://nsi.guide/?t=brands&tt={{name}}) to add the correct tags.`

It is working great when `name` does not contain any space:

![image](https://user-images.githubusercontent.com/6597721/225983018-902bedfe-08d3-421a-ad39-66f3c42ac818.png)

But with some spaces, the link is not working:
![image](https://user-images.githubusercontent.com/6597721/225983331-3af23851-d743-4ac0-9d66-4a6bdf5a1bcf.png)

**Describe the solution you'd like**

I am wondering if you can implement a "filter" for your [mustache tagging](https://learn.maproulette.org/documentation/mustache-tag-replacement/) like so:

`{{name|urlEncode}}`

So I can fix my issue like this:

`Use [nsi.guide](https://nsi.guide/?t=brands&tt={{name|urlEncode}}) to add the correct tags.`

The space will be converted to %20 and other special char like &, é, ... will also be encoded so this make my custom dynamic link to work. You can use the default javascript function encodeURIComponent that encode nicely all special chars

Here is an example:

`Use [nsi.guide](https://nsi.guide/?t=brands&tt=Les%20fen%C3%AAtres%20sont%20%2B%20vertes%20%26%20jaunes) to add the correct tags.`
=> Use [nsi.guide](https://nsi.guide/?t=brands&tt=Les%20fen%C3%AAtres%20sont%20%2B%20vertes%20%26%20jaunes) to add the correct tags.

**Describe alternatives you've considered**
Since my challenge is made with an overpass query, I can not encode the name with my overpass query because overpass does not support generating keys.

Have a nice day and thank for all your work on MapRoulette!

**Comment by tsun812** [comment]
To allow for spaces in url, you can wrap your url inside <>, so it would be something like ```[nsi.guide](<https://nsi.guide/?t=brands&tt=Petite Casino>)```

There is a relevant issue about this https://github.com/maproulette/maproulette3/issues/1950

**Comment by Binnette** [comment]
Great thanks @tsun812
