### ISSUE TITLE
Maxar Premium imagery does not load anymore in MapRoulette

### ISSUE THREAD

**Issue by Jorieke** [maproulette/maproulette3#1996]
**Describe the bug**
Maxar Premium imagery does not load anymore in MapRoulette. 

**Expected behavior**
If I open a challenge and want to switch the background of the map to Maxar Premium imagery it should give the Maxar Premium Imagery as a background, now it just gives a grey view.

**Screenshot**
![image](https://user-images.githubusercontent.com/6013645/229135697-e1667c5e-71f3-457d-86c1-f753bf7190b9.png)

**Desktop**
 - OS: Windows
 - Browser: Edge

**Comment by atiannicelli** [comment]
Confirmed. I believe this may be due to maxar unavailability. See: https://community.openstreetmap.org/t/maxar-imagery-not-working-was-maxar-is-blurred-in-id-and-other-similar-topics/100524/52

Probably we should remove the link or add a note that this source is currently unavailable.

**Comment by mvexel** [comment]
We will: 
* hide the link temporarily
* @mvexel will monitor the situation on the OSM side
