### ISSUE TITLE
Mapbox Satelite no longer loading - No value provided for variable {apikey}

### ISSUE THREAD

**Issue by Binnette** [maproulette/maproulette3#1998]
Here is the error message:

`Unable to render the map: No value provided for variable {apikey}. Attempting to fall back to default map layer.`

Have a nice day.

**Comment by mvexel** [comment]
Yes.
Let's resolve. Do we need a new api key? @tyrasd do you have any insight into this?

![image](https://github.com/maproulette/maproulette3/assets/120452/078b4f88-c8f9-4bc6-9547-713a8f7af68a)

**Comment by tyrasd** [comment]
The error message (`No value provided for variable {apikey}`) would indicate that this might be a configuration issue.[^1] The token I sent you on March 18th[^2] should still be active for the maproulette.org (and staging.maproulette.org) domain. Let me know if I should send it to you again.

[^1]: presumably on the server side where the main instance of maproulette is deployed
[^2]: note that the apikey should not be committed into the git repository here, and if that's not feasible, it should only be included in an [obfuscated](https://github.com/openstreetmap/iD/blob/v2.25.2/data/manual_imagery.json#L41) form.

**Comment by mvexel** [comment]
Thanks @tyrasd 
Looks to me like you are correct and we need to (re)configure this.

**Comment by jschwarz2030** [comment]
Per @mvexel might just need a new api key.

**Comment by AndrewPhilbin** [comment]
This has been solved via production .env without any code changes here and is working now, so I'll go ahead and close the issue.
