### ISSUE TITLE
Reporting challenge does not make clear that it will be posted immediately in a public view

### ISSUE THREAD

**Issue by matkoniecz** [maproulette/maproulette3#2002]
I think it should be clear to avoid someone unintentionally posting private info or doxxing themself by accident.

**Comment by mvexel** [comment]
I suggest to change the wording at the arrow (below) to "in this public github repository" and make that text link to https://github.com/maproulette/challenge-reports/issues

![image](https://user-images.githubusercontent.com/120452/232893256-f7bf0f60-39b7-4e17-941c-96279cb42fcd.png)
