### ISSUE TITLE
Provide more information on notification settings

### ISSUE THREAD

**Issue by danieldegroot2** [maproulette/maproulette3#2005]
The notification settings section is currently
* quite long (vertically), perhaps it would be better to start with two columns below the first 'address' setting; and
* unclear.
  * lacking description of actions which trigger a notification.
  * asterisks ('*') are not explained. Usually these mean something is required before saving, however settings auto-save.
  * errors are not explained / setting are bugged. Is the user unable to ignore these notifications? (other options: email daily, or weekly). I would assume the user is able to ignore them unless they are relevant for moderation.

![image](https://user-images.githubusercontent.com/67521919/232113760-c22934aa-978a-4603-a5b0-c9b6634f97e6.png)

**Comment by mvexel** [comment]
We will:
* remove the asterisks (they have no meaning)
* make the saving / saved indicator more visiblt
* Write tooltips @mvexel

**Comment by mvexel** [comment]
"Team" and "Follow" settings are not persisted

**Comment by mvexel** [comment]
Fill out the list here https://docs.google.com/spreadsheets/d/16KQKuYklSDNKB_Eeg1EWl2PcnSezrFmGzF_dMeQC6Ew/edit?usp=sharing
