### ISSUE TITLE
MapRoulette is down

### ISSUE THREAD

**Issue by TomaszKozlowski-TomTom** [maproulette/maproulette3#2011]
The tool is not working properly. We cannot load MapRoulette at all.

**Comment by sulfo** [comment]
@jschwarz2030 Seems like MapRoulette is down again?

**Comment by Openstreetmapler** [comment]
Down for me!

**Comment by jschwarz2030** [comment]
We are having periodic issues with leaderboard services hanging up the system.  Please avoid the leaderboard page while we continue to investigate
