### ISSUE TITLE
Clicking Edit for task flagging relation brings up editor with way instead

### ISSUE THREAD

**Issue by atiannicelli** [maproulette/maproulette3#2017]
**Description** 
I have a task that highlights a relation and when I click on the "edit" button it brings up an editor (I tried 3 different ones) with the way of the same number instead of the relation. 

**Expected behavior**
When I click on the edit button I expect that the editor will load up the relation having to do with the task.

**To Reproduce**
go to the following task:
https://maproulette.org/admin/project/51593/challenge/39279/task/161863677/inspect
Click on edit and observe that the url in the editor includes id=w9998598 instead of id=r9998598

Here is the geoJson from that task (in case it goes away)
```
{"type":"FeatureCollection","features":[{"type":"Feature","geometry":{"crs":{"type":"name","properties":{"name":"EPSG:0"}},"type":"Polygon","coordinates":[[[2.7187347,50.9030626],[2.7188465,50.903065],[2.7188552,50.9029041],[2.7187434,50.9029017],[2.7187347,50.9030626]]]},"properties":{"name":"Het Pahilleke","tourism":"guest_house","website":"https://www.pahilleke.be","building":"yes","identifier":"r9998598@2","instructions":"Relation 9998598 has no relation type.","osmIdentifier":"relation/9998598"}}]}
```

**Screenshots**
This first shot is of the task from map roulette
![Screenshot 2023-05-09 at 3 31 58 PM](https://github.com/maproulette/maproulette3/assets/5851115/77cfe0f2-7d64-4d60-b231-a851e7424935)
This second is what I get if my editor is set to rapid. Notice the URL and that the feature on the left is a way.
![Screenshot 2023-05-09 at 3 32 54 PM](https://github.com/maproulette/maproulette3/assets/5851115/34418504-d128-4b7b-bf2e-82aaa53a1bf8)

**Desktop (please complete the following information):**
 - OS: MAC
 - Browser: chrome
 - Version: 3.12.0

**Comment by tsun812** [comment]
Currently the relation is only bonded to MultiPolygon geometry type and way is of type Polygon, does it work if you set the type to Multipolygon?

**Comment by atiannicelli** [comment]
Well, that's the issue... My challenge is finding relations with bad or no types. So these relations might not have any type to start with. I was hoping that by using the "r" at the beginning of the OSM id that it would do the right thing..

**Comment by tsun812** [comment]
I tried to set the geometry type to MultiPolygon with your geojson but it doesn't build tasks properly.
Right now we don't parse from OSM id when constructing URI for the editor, only from geometry type, that's why it's not working as expected.
One way to get around it is to parse from OSM Identifier so it takes precedence over geometry type. I will create a pr for this if this sounds good to you.

**Comment by atiannicelli** [comment]
That sounds great. I would think that we could look at the identifier to see if it has the [n|w|r] letter to start and use that if it is there. if the identifier is just a number then fall back to what you do now.
