### ISSUE TITLE
Interfaces Cycles Forever Between Small Number of Tasks Previously Resolved as 'Too Hard'

### ISSUE THREAD

**Issue by lmmcgov** [maproulette/maproulette3#2018]
**Description of  bug**
There are **at least two** road challenges with similar bugs. For the first (https://maproulette.org/browse/challenges/38903) approximately the first two dozen tasks that I worked involved roads of tertiary classification and higher. After finishing these tasks, marking many as 'too hard', it was observed that the browser maproulette interface returns to these 'too hard' tasks ad-infinitum. Any substantial progress is impossible as only a very small subset of tasks are accessible with Maproulette constantly cycling back to 'too hard' tasks previously completed. I tested a similar project for another country and observed the same problem (https://maproulette.org/browse/challenges/38930)

**Expected behavior**
All tasks should be accessible after resolving or skipping. 

**To Reproduce bug for project 38903**
1. Go to https://maproulette.org/browse/challenges/38903
3. Click on the Start button, automatically populates the interface with a task marked previously as 'too hard'
4. Click on Next Task, populates the interface with a task marked previously as 'too hard'
5. Click on Next Task, populates the interface with a task marked previously as 'too hard'
6. Click on Next Task, populates the interface with a task marked previously as 'too hard'
7. Error repeats forever, never progressing to a fresh task

**To Reproduce similar bug for project 38930**
1. Go to https://maproulette.org/browse/challenges/38930
3. Click on the Start button, automatically populates the interface with a task marked previously as 'too hard'
4. Click on Next Task, populates the interface with a task marked previously as 'too hard'
5. Click on Next Task, populates the interface with a task marked previously as 'too hard'
6. Click on Next Task, populates the interface with a task marked previously as 'too hard'
7. Error repeats several times, before the interface eventually populates with a 'Challenge End' graphic

**Screenshots for https://maproulette.org/browse/challenges/38903**

Screenshot for step 3
![Screenshot 2023-05-11 at 1 22 56 PM](https://github.com/maproulette/maproulette3/assets/69876178/1e81c551-a8ac-4c93-99c9-e118e02e955a)

Screenshot for step 4
![Screenshot 2023-05-11 at 1 22 45 PM](https://github.com/maproulette/maproulette3/assets/69876178/b577cffb-f8b7-4565-adb9-e091988b6af6)

Screenshot for step 5
![Screenshot 2023-05-11 at 1 32 54 PM](https://github.com/maproulette/maproulette3/assets/69876178/c0aeff24-51b9-4517-96a9-77103cb65170)

**Screenshots for https://maproulette.org/browse/challenges/38930**
![Screenshot 2023-05-11 at 1 38 21 PM](https://github.com/maproulette/maproulette3/assets/69876178/33292fb3-fa7e-4e2a-9bb7-c5b0adb7c3af)

**Desktop information:**
 - OS: Ventura 13.0.1
 - Browser Chrome (same problem occurs using Safari)
 - MapRoulette [v3.12.0](https://github.com/maproulette/maproulette3/releases/tag/v3.12.0)

**Comment by mvexel** [comment]
We'll investigate and follow up, thanks for reporting
