### ISSUE TITLE
Large "test" challenges -- how to deal?

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette3#2020]
Sometimes large challenges pop up that seem to be just test challenges. [Here's an example](https://maproulette.org/browse/challenges/39338).

What mechanisms can we come up with to mitigate test tasks polluting the task pool? This is off-putting to people looking for meaningful tasks to do.

A follow up email? A warning that you are about to create a large challenge? Have challenges be non-discoverable by default? #1741 should help a little also.

Please help generate good ideas for this :)

**Comment by mvexel** [comment]
Other option -- by default make challenge is not discoverable?

**Comment by mvexel** [comment]
Or, a sandbox project where everyone can create test challenges

**Comment by ljdelight** [comment]
The staging environment would be a great place to test out those sort of tests. Standard users wouldn't be aware of it ofc https://staging.maproulette.org/

**Comment by emvee-osm** [comment]
Apart from a making the challenges not discoverable by default and making that staging area more know I think it is good to check challenges say once every two month and if during that month no progress is made make the challenges not discoverable and mail the owner about this and an ask to review things.

**Comment by CollinBeczak** [comment]
I agree that the staging environment should be more well known. I could add a banner like so:
![Image](https://github.com/user-attachments/assets/048e3ba5-1e63-49d1-8d3a-73d1f30b850d)
I'm open to other implementations of this notice, wether that be putting it directly into the project/challenge creation forms, or just regularly letting the community know it exists via social media.

I think it would be a good idea moving forward with making staging more well known and making challenges not discoverable by default. 
If we want to move forward with the other suggestion:
> check challenges say once every two month and if during that month no progress is made make the challenges not discoverable and mail the owner about this and an ask to review things.

I'd separate that into another ticket.

**Comment by jake-low** [comment]
I like the idea of a banner on the challenge creation form suggesting that people can use staging to test out their challenges if they want before creating them in prod. We could also add a similar message in the challenge creation docs on learn.maproulette.org.

@mvexel pointed out that if we start making staging more discoverable by end users, we ought to add some kind of bright colored banner or similar on the staging server frontend so that people don't get confused and start completing tasks there instead of on prod.

**Comment by mvexel** [comment]
The audience for awareness of staging is just folks who are planning to create a challenge and want to experiment in a safe environment first without cluttering up prod.

In light of that I'd prefer it if the notification would appear in the create challenge form rather than on the main page where most people are not part of that audience.

Making challenges not discoverable by default is a great little improvement, I'm all for it.
