### ISSUE TITLE
Unable to mark challenge as favourite from main challenge page

### ISSUE THREAD

**Issue by Xandaros** [maproulette/maproulette3#2025]
**Describe the bug**
Attempting to mark a challenge as favourite from the main challenge description page results in this error message:

> Oops!
>
>   Unable to save your changes{details}
>   Unable to retrieve latest challenge data from server.

Marking a challenge from the task page does work. Unfavouriting also works, even from the challenge page.

**Expected behavior**
Clicking the "Favourite" button should mark the challenge as favourite and not show an error message.

**To Reproduce**
1. Open a challenge, e.g. [Convert playground node to area - World](https://maproulette.org/browse/challenges/38575)
2. Click the "Favorite" button

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 112.0.2 (64-bit)

**Comment by jschwarz2030** [comment]
resolved by https://github.com/maproulette/maproulette3/pull/2030
