### ISSUE TITLE
Duplication of tasks

### ISSUE THREAD

**Issue by UNMappers** [maproulette/maproulette3#2031]
[Challenge 39495](https://maproulette.org/browse/challenges/39495) has seen its initial number of 903 tasks (provided by a geojson file hosted on gist that you can find [here](https://gist.github.com/severinmenard/d6cb6bd2cc9db6a641ce9e1889600a00)) been x3. I had noticed on a previous challenge with the same tasks source that any edit of its instructions or description added the 903 tasks again, creating duplicated tasks (despite every task having an ID). 

Therefore, Challenge #39495 was created "once for all" but despite not being edited, it it reaches now 2,709 tasks. I don't know if it's related to the server problems MapRoulette had yesterday and today.

**Comment by jschwarz2030** [comment]
I'm seeing a couple problems with the geojson on this challenge.  One solution is to change your format from  `{ "ID": 1 }` to `{ "id": "1" }`.  Ensure the unique identifier is a string, not an integer, and also that your id param is one of the following (case sensitive):

```
id
@id
osmid
osm_id
name
```

But if you want to use a custom external id like all-caps `ID`, be sure to add it as your External ID when you create the challenge.  Do note that this feature also requires that your unique identifiers are strings.

https://learn.maproulette.org/documentation/setting-external-task-identifiers/
