### ISSUE TITLE
OSM-Wiki MapRoulette/Challenges page

### ISSUE THREAD

**Issue by 501Ghost** [maproulette/maproulette3#2060]
On the OSM Wiki there is a page called [MapRoulette/Challenges](https://wiki.openstreetmap.org/wiki/MapRoulette/Challenges). The talk page hasn't been touched since 2014. Does this page still serve a purpose or can it be marked for deletion?

**Comment by mvexel** [comment]
It can be marked for deletion. Thanks for raising it.

**Comment by Tigerfell** [comment]
Well, it is usually not that helpful to request deletion of singular pages without fixing the links to that page. I noted that on your request instead of deleting the page (per normal procedure).
