### ISSUE TITLE
Support opening links in new tab

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette3#2064]
When I include links in the description, I usually want those to open in a new tab. I can instruct the user to control-click to do that, but it would be nicer to directly support this, either by allowing HTML code like `<a href...` in the description markdown or by making this a setting when you create the challenge (offered as a toggle underneath the description field). The latter is preferred, because no common markdown spec that I know of allows `<a></a>` HTML blocks.

**Comment by tsun812** [comment]
seems like it's supported already, [maproulette](https://www.maproulette.org) allows me to open in new tab. does it not work for you?
