### ISSUE TITLE
When multiple people access the same challenge, the site is not responding

### ISSUE THREAD

**Issue by hcyen1966** [maproulette/maproulette3#2129]
We held a gathering to show people about Maproulette Challenges, and there were about 15 people in the same meeting room. When we tried to access, the site is not responding. I don't know if there is a limitation of number of people accessing the challenge. 

Sorry I don't have screen capture.

**Comment by CollinBeczak** [comment]
Would you be able to give the challenge link and describe what the page looked like when it wasn't responding? Wether you got an error message, a white screen, or a blue screen would be helpful information. Thank you for letting us know about this!

**Comment by salimbaidoun-tomtom** [comment]
Hello MapRoulette devs, 

MapRoulette has exhibited significant performance issues over the past two weeks, consistently encountering glitches during editing sessions and live demonstrations. It remains unclear whether this is a result of multiple people or editors joining simultaneously, but the tool's stability is compromised. I'm attaching a link to a video illustrating the daily challenges I personally face.

https://shared-assets.adobe.com/link/689cd510-68ba-46da-76ef-f5b139ad8406 

thank you.

**Comment by jschwarz2030** [comment]
Apologies for the continued performance issues you are facing.  While system stability has been a primary focus, we are aware of a systemic architectural decision in the API that makes some features reliant on ever-growing soft-deleted data.  We want to move away from this architecture and will be addressing it in the upcoming milestone.

**Comment by CollinBeczak** [comment]
Resolved by:  maproulette/maproulette-backend#1105
