### ISSUE TITLE
Point to automated edits policy when creating a new challenge

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette3#2131]
At the top of the Create Challenge screen, we should add a prominent warning box that makes it very clear that MapRoulette challenges are meant for careful human review. We should add a link to the OSM [automated edits guidelines] that 

We should add a checkmark that the user must check to acknowledge that they have read and understand this warning.

Exact wording to be defined.

**Comment by mvexel** [comment]
Here's the wording I suggest, Let's discuss where to make it appear. Options are
1. At the top of the challenge create flow
2. At the bottom by the "create challenge" button
3. As a modal when you start creating
4. As a modal after you click "create challenge"

You're about to create a MapRoulette challenge. With this power comes responsibility. Make sure that your Challenge is designed to encourage careful human attention to each task, in the spirit of OpenStreetMap's [Automated Edits code of conduct](https://wiki.openstreetmap.org/wiki/Automated_Edits_code_of_conduct). Please read this document carefully. By checking the box below, you acknowledge that you understand and accept this responsibility. <checkbox>

We need to solve for API based challenge creation. Perhaps display the same "contract" when creating an API key.

**Comment by AndrewPhilbin** [comment]
I'm thinking option 2 with a required checkbox might be the least obtrusive location but that still requires sufficient user acknowledgement/interaction.

**Comment by mvexel** [comment]
makes sense. Let's make it so!

**Comment by mvexel** [comment]
In addition we will collapse the optional sections by default. Need to find a path towards deprecation of the wizard style form @mvexel
