### ISSUE TITLE
Cannot create MapRoulette challenge

### ISSUE THREAD

**Issue by TomaszKozlowski-TomTom** [maproulette/maproulette3#2137]
Cannot create MapRoulette challenge.

**Expected behavior**
After filling out a form for challenge creation and finishing this action, MapRoulette is not responsing (the wheel turns constantly). 

**To Reproduce**
1. Go to 'Create Challenge'
2. Fill out the form.
3. Push 'Finish' button.

**Additional context**
Workaround is to clone existing challenge and change the details within.

**Comment by ljdelight** [comment]
I see this too, console log shows "Uncaught (in promise) TypeError: r.taskWidgetLayout is undefined" and there is no request to the backend for the create.

**Comment by ljdelight** [comment]
Thank you for the report @TomaszKozlowski-TomTom . We backed out a release so that challenges can be created.
Fix for trunk is #2138

**Comment by ljdelight** [comment]
Resolved with release v3.13.2-rev1
