### ISSUE TITLE
Unable to create a virtual challenge: ERROR: duplicate key value violates unique constraint "con_virtual_challenges_user_id_name" Detail: Key (owner_id, name)= (1041828,) already exists.

### ISSUE THREAD

**Issue by govvin** [maproulette/maproulette3#2150]
**Describe the bug**
When I create a virtual challenge with an empty name, I get this error:
"Unable to create a virtual challenge: ERROR: duplicate key value violates unique constraint "con_virtual_challenges_user_id_name" Detail: Key (owner_id, name)= (1041828,) already exists."

I was able to create one nameless virtual challenge prior to this, but I supposed that key has been "taken" now and can't be used.

**Expected behavior**
Can we make virtual challenge names optional, for one-time use of virtual challenges??

My use case would be, for example, I'd like to work on this particular area just for next hour, and I have no plans of sharing it with anyone. I can come back to the same area, and review whatever task is left again the following day, and I can just re-create a new virtual challenge, which I may want to share a friend.

**To Reproduce**
1. Open an MR challenge
2. Click on the lasso tool to select tasks you want to include in the Virtual Challenge
3. Click on "Work on selected ... tasks"
4. If it's your first time to create a nameless challenge, there won't be an error. You'll get the error message on succeeding ones. 

**Screenshots**
![image](https://github.com/maproulette/maproulette3/assets/5821688/917df40a-d40e-439e-bff2-e6ecb08932ee)

**Desktop (please complete the following information):**
 - OS: PopOS!
 - Browser Firefox v 118.0.2

**Comment by mvexel** [comment]
Let's keep the unique constraint on regular challenges
