### ISSUE TITLE
Attempting to close a note results in a login reset in RapiD's inbuilt editor.

### ISSUE THREAD

**Issue by deevroman** [maproulette/maproulette3#2173]
**Describe the bug**
Attempting to close a note results in a login reset in RapiD's inbuilt editor.

**Expected behavior**
The note should close.

**To Reproduce**

1. Open any challenge
2. Switch on Edit mode
3. Switch on the notes layer
4. Find a note and close it
5. You are prompted to log in again.

**Screenshots**

https://github.com/maproulette/maproulette3/assets/25708359/a02dedbd-deed-49af-a50d-91ba2dd9ecf5

**Desktop (please complete the following information):**
 - OS: macOS 14
 - Browser firefox/chrome
 - Version 120/119

**Comment by jschwarz2030** [comment]
added Modify Notes to the OSM key
