### ISSUE TITLE
Upgrade to Tailwind v3

### ISSUE THREAD

**Issue by jschwarz2030** [maproulette/maproulette3#2174]
We are currently on version 2 and need to upgrade to version 3, as well as upgrade all of the associated tailwind libraries.

We should also remove the `mr-` prefix, which I believe was incorporated so that we didn’t have css naming overlap with other styling libraries.

**Comment by AndrewPhilbin** [comment]
I looked into this fairly thoroughly. It seems like removing the `mr-` prefix is a worthy endeavor. It's not trivial as there are still non-Tailwind classes that use this prefix that would need to be left alone. There isn't really a clean way to allow both prefixed and non-prefixed Tailwind classes, so the change would have to include any and all Tailwind class usage in one fell swoop. It might be possible to have multiple entry points for Tailwind to allow for a more incremental removal, but this seems like more trouble than it's worth.

As far as upgrading Tailwind: we have a number of legacy plugins and dependencies that need to be assessed for compatibility. Some will pretty clearly work without much issue after some simple config changes, while others may or may not be able to get along with Tailwind 3 depending on whether the classes they generate interfere. Still others, like the `tailwind-grid` plugin, might better be replaced by standard Tailwind grid utilities, depending on how much they are used throughout the app.

I think I'll probably split these two tasks into separate tickets or at least separate PRs, with the prefix-removal taking priority.
