### ISSUE TITLE
Review permission in Transifex

### ISSUE THREAD

**Issue by matheusgomesms** [maproulette/maproulette3#2178]
Hey guys!

I noticed that several strings in PT-BR are not translated (empty), are in English (don't know why) or are not reviewed, making it very difficult to finish all translations in a easier way (only 98 strings theoretically untranslated, which is not the real case). This is a follow up from #663.

Could you please add me as a PT-BR reviewer in Transifex? That way, I can review all strings and make life easier for future translators.

I'm also a translator for iD, JOSM, Organic Maps, EveryDoor and some other OSM softwares. My username there is matheusgomesms.

Thanks a lot!

**Comment by matheusgomesms** [comment]
Update: at least I managed to delete several English strings at once, so at least I can work on these empty translations as a start. I suppose this is okay (I think if there is no translation, EN is used as a fallback).

**Comment by jschwarz2030** [comment]
I'm not seeing an option to add a role for "Reviewer", and the only current role we have in place is "Project Maintainer".  Perhaps @mvexel knows a better protocol on how to proceed here.

**Comment by mvexel** [comment]
I'm not completely sure how roles work on Transifex but I made you "Coordinator" for PT-BR @matheusgomesms 
Please feel free to close this issue if that does what you want.

**Comment by matheusgomesms** [comment]
Yep, I think it works now, thanks a lot Martijn! I'll bother you all again when I finish work on and review all strings, which I'll start by late January. Happy holidays!

**Comment by mvexel** [comment]
Awesome! Happy holidays Matheus!

**Comment by matheusgomesms** [comment]
Hi all! Just to let you know that I finally finished Portuguese (Brazil) translation! I know the updated strings will come on the next release, but wanted to have it clear here for future reference. :)
