### ISSUE TITLE
Translation not correct on the Dashboard page https://maproulette.org/dashboard

### ISSUE THREAD

**Issue by pelderson** [maproulette/maproulette3#2190]
The personal statistics statement on the front page in the Dutch language is not correct Dutch. 
![image](https://github.com/maproulette/maproulette3/assets/38458314/89b6b463-a987-4113-924a-96b51fbc5afe)

I can't find these text fragments in Transifex/Maproulette3. How can I correct this?

**Comment by mvexel** [comment]
Hey, thanks for looking into this!
You will need to look for "translated text", for example [text:earned translation_text:verdiend](https://app.transifex.com/osmlab/maproulette3/translate/#nl/en-us-json?q=text%3Aearned+translation_text%3Averdiend)
Let us know as a comment here if / when you fixed the translation so we can close the ticket, thanks!

**Comment by mvexel** [comment]
I also don't particularly like "Uitdaging" as a translation for "Challenge"... What do you think @pelderson ?

Perhaps I've been away from NL too long to assess this correctly..

**Comment by pelderson** [comment]
I just thought of a word: I think "Missie" catches the idea perfectly.

**Comment by mvexel** [comment]
Thanks for thinking through this! I like "Missie". Could you make the necessary changes?

**Comment by pelderson** [comment]
Done. Can't wait to see it released! I thin this issue can be closed.

**Comment by mvexel** [comment]
Thanks again @pelderson ! I will close this issue now. The updated translations will be included in the next release. We usually release once a month but because of the holiday season I am not sure if we'll do a December release.
