### ISSUE TITLE
"Group by Task" in https://maproulette.org/inbox causes only last message to be shown

### ISSUE THREAD

**Issue by matkoniecz** [maproulette/maproulette3#2200]
**Describe the bug**

"Group by Task" in https://maproulette.org/inbox causes only last message to be shown

**Expected behavior**

"Group by Task" in https://maproulette.org/inbox causes messages to be grouped by task

**To Reproduce**
1. Get messages
2. Log in
3. Open https://maproulette.org/inbox

**Screenshots**

![screen10](https://github.com/maproulette/maproulette3/assets/899988/80c03127-af5c-418f-a377-060ac453b905)
![screen11](https://github.com/maproulette/maproulette3/assets/899988/eca7a883-af8c-4fdc-81e4-0f4baf671905)

**Desktop (please complete the following information):**
 - OS: Lubuntu (Linux -> Ubuntu)
 - Browser Firefox
 - Version 120

**Additional context**

Not sure what is the point of this setting.

**Comment by CollinBeczak** [comment]
To me this appears to be functioning normally, it displays the most recent status, and groups that tasks by id ( in the first image in the task column ) it says you have 32 task with that id. **It is weird that no task Id is being displayed, but they are still grouping as they should be.**
<img width="1100" alt="Screenshot 2023-12-18 at 8 16 39 AM" src="https://github.com/maproulette/maproulette3/assets/88843144/db3684e0-d248-41ed-8026-b5aab6756edc">
As for the usefulness of this feature, it changes what the modal displays. If there is no grouping, it will only display the individual task in the modal popup.
<img width="764" alt="Screenshot 2023-12-18 at 8 22 11 AM" src="https://github.com/maproulette/maproulette3/assets/88843144/fd7c60f1-6681-4eae-a107-9f6926bd5336">
But if you group tasks by id, it will show the list a newest to oldest order from top to bottom.
<img width="861" alt="Screenshot 2023-12-18 at 8 22 33 AM" src="https://github.com/maproulette/maproulette3/assets/88843144/08789dcb-1a98-4339-a940-8028646447e1">

This can be useful for some users in visualizing the history of a task.

**Comment by matkoniecz** [comment]
Are https://maproulette.org/browse/challenges/40173?tab=conversation and https://maproulette.org/browse/challenges/36420?tab=conversation supposed to be grouped as single task? Because for me these are.

**Comment by CollinBeczak** [comment]
Definitely not, ill look to see if there are any conditions that enable all tasks to be grouped together. To confirm, when you group by task, every single task in the table gets grouped together?

**Comment by matkoniecz** [comment]
yes

maybe they are not showing their ids because somehow it is null?

**Comment by CollinBeczak** [comment]
It looks like challenge comments are not linked to a particular task, so since they have an equal null value they get grouped. I will make it so that challenge comments are not grouped when group by task is selected for now.

**Comment by CollinBeczak** [comment]
After looking into this more, I thought it would be weird for challenge comments to not have the functionality of grouping. So I made them group by challenge name. Let me know if this resolves your problem with the feature. 
<img width="1032" alt="Screenshot 2023-12-18 at 12 55 56 PM" src="https://github.com/maproulette/maproulette3/assets/88843144/b84e78f7-db01-44c0-8c64-20e75b5e4309">

<img width="761" alt="Screenshot 2023-12-18 at 12 59 20 PM" src="https://github.com/maproulette/maproulette3/assets/88843144/3538efee-5329-4056-873d-7921c3b0bb60">

**Comment by matkoniecz** [comment]
I guess that root cause is missing id, but grouping by name should work, I guess
