### ISSUE TITLE
Unable to create a collaborative challenge with more than 2378 tasks

### ISSUE THREAD

**Issue by archie83** [maproulette/maproulette3#2203]
**Please Read First**
* If you are having **issues creating your own Challenges**, please make sure you carefully read the MapRoulette [documentation](https://learn.maproulette.org/documentation/), specifically the section about Creating and Managing Challenges. If that doesn't help you, please post to the [OSM community forum](https://community.openstreetmap.org) with the hashtag **#maproulette**. 
* If you would like to report a Challenge you think is causing bad edits to OSM, please raise the issue with the Challenge owner first using the *Get In Touch* feature on the Challenge home page. If they fail to respond, please post to the [OSM community forum](https://community.openstreetmap.org) with the hashtag **#maproulette**.
* There is a [separate repository for the MapRoulette back end](https://github.com/maproulette/maproulette-backend/issues). If your report pertains to the API / back end, please submit it there.

Thanks for helping us make MapRoulette great for everyone!

**Describe the bug**
I'm trying to create a collaborative challenge by importing a GeoJSON file that contains approximately 12000 lines. But MapRoulette displays only 2378 tasks. Example: https://maproulette.org/admin/project/54580/challenge/42483

**Expected behavior**
MapRoulette should display 12000 tasks.

**To Reproduce**
1. Create a new challenge 
2. I want to upload a GeoJSON file
3. Select  the peaks.geojson file (unzip [peaks.zip](https://github.com/maproulette/maproulette3/files/13641284/peaks.zip))
4. When importation is finished, refresh the page and look at the number of tasks.

**Desktop (please complete the following information):**
 - OS: [Linux]
 - Browser [Firefox]
 - Version [e.g. 120]

**Comment by mvexel** [comment]
There seem to be a lot of duplicates in the GeoJSON you provided. Please try with duplicates removed. If that doesn't help, feel free to re-open this issue.
