### ISSUE TITLE
Blank page on direct link to task or challenge

### ISSUE THREAD

**Issue by atiannicelli** [maproulette/maproulette3#2210]
If I give someone a link to a challenge like this: https://maproulette.org/challenge/42081
and they click it without being logged into Map Roulette then it turns into this: https://maproulette.org/challenge/42081/task/203145507 (or some task)
But the page goes blank!!!

**Expected behavior**
I expected to be given a page to login and then be directed to the task.
Or - just send me to the challenge overview page.

**To Reproduce**
logout of mr
goto: https://maproulette.org/challenge/42081

**Screenshots**
just blank

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser chrome
 - Version [v3.14.2](https://github.com/maproulette/maproulette3/releases/tag/v3.14.2)

**Comment by atiannicelli** [comment]
So the real problem here is that jumping directly to a task gives a blank page if they are not logged in. That means that if I give a link to a task to a firend and they haven't logged in then they will get a blank screen... or, for the rapid team that is trying to integrate MR into rapid , then if they direct a user to a task page on MR then they get a blank page.

**Comment by ljdelight** [comment]
> jumping directly to a task gives a blank page if they are not logged in

Yup I see that too. Similar if the challenge doesn't exist, logged in or not (https://maproulette.org/challenge/asdfsdfkdfkekf ).

I'll note a possible workaround if you're only after the Challenge overview page. If you'd rather see the challenge overview page, use [/browse/challenges/42081](https://maproulette.org/browse/challenges/42081) or a recent patch allowed shorter URLs such as <https://maproulette.org/c/42081> or <https://mpr.lt/c/42081>. There's a short url for tasks too, such as <https://mpr.lt/c/42081/t/203145507> but if the user isn't logged in, it will end up in the same broken state you mentioned above.
