### ISSUE TITLE
Cannot upload geojson file to the challenge

### ISSUE THREAD

**Issue by TomaszKozlowski-TomTom** [maproulette/maproulette3#2218]
**Describe the bug**
While challenge creation, I cannot upload geojson file, because of an error.

**Expected behavior**
After choosing upload geojson file option, challenge creation should be possible - moving to another tab should be allowed. It is not.

**To Reproduce**
1. Go to 'Create Challenge'
2. Click on 'Upload geojson file' for the source
3. Choose a file
4. Click 'Next' button
5. An error: "GeoJSON error: Invalid GeoJSON geometry" appears.

**Screenshots**
![image](https://github.com/maproulette/maproulette3/assets/89768710/ce156814-9b22-4c0d-8894-b983cdc8453a)

**Desktop (please complete the following information):**
 - Windows
 - chrome

**Comment by CollinBeczak** [comment]
The step by step form functions differently at the moment, and has a slightly different way of validating than the long form. While we solve this issue, you should be able to use the long form( in the upper right of the form there are two icons, click on the list icon )

**Comment by MikeTho16** [comment]
I tried the long form, and indeed I didn't get any error messages, however, when I actually start the challenge, nothing is loaded into JOSM (it is a cooperative challenge).  I do get an empty layer added to JOSM: "MR TASK 207677256 Changes." I generated the geojson file as follows:
$ mr cooperative change --out AlaskaSummits.json --bijective ./out/*.osm

I have attached the resulting AlaskaSummits.json
[AlaskaSummits.json](https://github.com/maproulette/maproulette3/files/13762986/AlaskaSummits.json)

I am able to participate in other MR challenges.

**Comment by CollinBeczak** [comment]
**Working:**
Json in file
{"type":"Feature","geometry":{"type": "Point", "coordinates": [-83.39500530998, 44.90348075341]},"properties":{"@id": "node/-138930", "note": "Great Lakes Access", "leisure": "slipway",  "mr_tags": null, "operator": "Michigan Department of Natural Resources", "mr_mapper": null, "mr_taskId": "135766467", "ownership": "state", "mr_mappedOn": "2022-11-01T13:53:00+00:00", "mr_reviewer": null, "mr_taskName": "node/-139137", "mr_responses": null, "mr_reviewedAt": null, "mr_taskStatus": "Fixed", "operator:type": "public", "mr_challengeId": "28620", "operator:short": "Michigan DNR", "mr_reviewStatus": null, "mr_taskPriority": "High", "operator:wikidata": "Q6837532", "operator:wikipedia": "en:Michigan Department of Natural Resources", "mr_reviewTimeSeconds": null}}

Maproulette task json
{"type":"FeatureCollection","features":[{"type":"Feature","geometry":{"type":"Point","coordinates":[-85.00448398532,44.60614181319]},"properties":{"@id":"node/-139175","access":"canoe","leisure":"slipway","operator":"Michigan Department of Natural Resources","ownership":"state","operator:type":"public","operator:short":"Michigan DNR","operator:wikidata":"Q6837532","operator:wikipedia":"en:Michigan Department of Natural Resources"}}]}

-----------------------------------------------------------------------------

**Not working:**
Json in file
{"type":"FeatureCollection","features":[{"type":"Feature","properties":{"gnis:feature_id":"1875756","gnis:reviewed":"no","name":"Mount Pangnik","natural":"peak","@id":"node/-28836"},"geometry":{"type":"Point","coordinates":[-144.89061683826,69.18011310769]}}],"cooperativeWork":{"meta":{"version":2,"type":2},"file":{"type":"xml","format":"osc","encoding":"base64","content":"PD94bWwgdmVyc2lvbj0nMS4wJyBlbmNvZGluZz0nVVRGLTgnPz4KPG9zbUNoYW5nZSB2ZXJzaW9uPScwLjYnPgo8L29zbUNoYW5nZT4="}}}

Maproulette task json
{"type":"FeatureCollection","features":[{"type":"Feature","geometry":{"type":"Point","coordinates":[-152.42667763829,61.16082413221]},"properties":{"@id":"node/-28574","name":"Ch'akajabena Mountain","natural":"peak","gnis:reviewed":"no","gnis:feature_id":"2076272"}}]}

-----------------------------------------------------------------------------

There are some different object names in your failing geojson that were generated that have the same purpose as differently named objects in the working geojson. This is likely your issue and a naming mismatch in the request to JSOM. The problem outcomes of the redirect to JSOM from your file i can see is the tasks "pin" not rendering, and for me at least the map isnt rendering area. I will ask around to see if there is either a new command for geojson that generates the working structure, or if we should implement compatibility for the object names in your json
