### ISSUE TITLE
Spinning beachball on dropping GeoJSON file in Challenge create

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette3#222]
Dropping attached file on the Local File field causes a spinning beachball in Safari / Mac.

[missingRdsCol.geojson.zip](https://github.com/maproulette/maproulette3/files/1848817/missingRdsCol.geojson.zip)

**Comment by mvexel** [comment]
Confirming that using the OS file chooser to upload leads to the same deadlock

**Comment by mvexel** [comment]
The file I used was the GeoJSON file, not the zipped file that I created for the purpose of uploading to GitHub

**Comment by mvexel** [comment]
Was this deployed in beta 3? I'm still seeing the issue.

**Comment by nrotstan** [comment]
No, it will be in beta.4

**Comment by mvexel** [comment]
Okay. Using remote GeoJSON is a workaround for now.

**Comment by nrotstan** [comment]
Yes, or using Chrome to create challenges with local GeoJSON.
