### ISSUE TITLE
The leaderboard freezes MapRoulette

### ISSUE THREAD

**Issue by kechan000** [maproulette/maproulette3#2224]
When you click the "View Leaderboard" button, the screen freezes on a loading screen and it never loads. 

Here is what it looks like: https://www.youtube.com/watch?v=848ZSknwlZg

**Comment by ljdelight** [comment]
Confirmed. I've been looking into this area on the backend.
- URL: https://maproulette.org/challenge/40342/leaderboard
- Problem APIs:
  - Task cluster took 22s to complete <https://maproulette.org/api/v2/taskCluster?ca=true&cid=40342&invf=&points=25&tbb=-147.74414062500003%2C19.145168196205297%2C-48.42773437500001%2C53.69670647530323>
  - `/api/v2/data/user/leaderboard` is the issue and hit the 75s timeout, resulting in http 502 <https://maproulette.org/api/v2/data/user/leaderboard?cLocal=1&challengeIds=40342&limit=10&monthDuration=-1&onlyEnabled=false>

After the API requests fail, the FE remains in the "loading" interface so there's an error path that needs to be improved. At least I didn't see an error dialog nor a console log.
