### ISSUE TITLE
Challenge `/browse` link does not always show challenge

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette3#224]
A `browse` link like http://maproulette.org/mr3/browse/challenges/2871 is a great way to share a Challenge with friends etc.

However, the receiving user does not always see the challenge when they click on the link, and it's unclear why.

@iandees reported clicking on the link in this message and seeing the splash screen, and upon dismissing this, the full list. https://lists.openstreetmap.org/pipermail/talk-us/2018-March/018455.html He did not have any filters enabled.

When trying to reproduce, I noticed that the Challenge also does not show when I previously enabled filters that would exclude the designated Challenge from the list.

*Expected behavior* is that if the user enters MR from a browse link, it should always show the Challenge (skipping the splash screen), unless it's been deleted or completed, in which case it should show a message to that effect.

**Comment by iandees** [comment]
Not sure how often you promote your stages, but this is still happening on e.g. http://maproulette.org/mr3/browse/challenges/2937.

**Comment by nrotstan** [comment]
Thanks for the report @iandees, the latest code (beta.3) will probably be deployed later today or tomorrow. I should have waited until then to close the issue. If you do see it once beta.3 is live, please do reopen the issue. To see the current version, you can click "About" in the top nav and then look at the very bottom of the dialog box that opens.

<img width="482" alt="about" src="https://user-images.githubusercontent.com/445970/37991915-4ad7c83a-31bf-11e8-91ab-36b5863d332d.png">
