### ISSUE TITLE
cool shortlinks with mpr.lt

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette3#225]
I just bought 'mpr.lt' so now we can create cool shortlinks.

Like mpr.lt/777 for challenge 777 or mpr.lt/mvexel for my (public) profile page (which we don't have yet).

**Comment by mvexel** [comment]
This also proves you can still get a 3 letter TLD for $20! (if you're okay with a Lithuania TLD)

**Comment by nrotstan** [comment]
We'll need to be able to distinguish between standard challenges and virtual challenges, as they have overlapping ids. So maybe mpr.lt/c/777 and mpr.lt/v/777?

**Comment by mvexel** [comment]
btw right now when you go to mpr.lt/mr3 and sign in, it won't acknowledge the OAuth authentication flow, probably either because the callback URL does not correspond, or routing in the application?

**Comment by nrotstan** [comment]
We'll want to redirect those short links to the normal urls when users initially follow them, and then everything in the app would continue work off the standard urls.

**Comment by habi** [comment]
I love the idea of the short links, but ran into a problem using it.
- Go to http://mpr.lt/
- Click sign in on the top right
- Get forwarded to OSM to 'Authorise the account'
- Get redirected back to Maproulette, but get shown an error that I have to sign in.

Screencast is shown here: http://youtu.be/e4uF54LrlhQ?hd=1

PS: Logging in to http://maproulette.org/ works just fine :)

**Comment by nrotstan** [comment]
Correct, at the moment using anything other than maproulette.org to sign in won't work. The short links should ultimately redirect to a maproulette.org URL once we add support for them.

**Comment by mvexel** [comment]
This received a good number of 👍 so let's do it!

**Comment by mvexel** [comment]
Now that we have #849 addressing #178 we can do this. 

What would be required is `mpr.lt` DNS records pointing to the maproulette server, and some rewrite rules in Apache / nginx ? Anything else?

**Comment by mvexel** [comment]
Closing this in favor of #178

**Comment by mvexel** [comment]
We should be able to link to:

* Public Challenge 'browse' pages `https://mpr.lt/c/challenge_id`
* Public Project pages `https://mpr.lt/p/project_id`
* Public task landing pages with https://mpr.lt/c/challenge_id/t/task_id (once we have #1593)

I think that should be enough for the moment!

**Comment by ljdelight** [comment]
This can be implemented using an nginx configuration change to capture `/p/<id>`, `/c/<id>`, `/c/<cid>/t/<tid>` and redirect as necessary. Nginx conf changes can't do much more than  basic matches so if more logic is necessary, then a backend endpoint will need to be created to do that additional logic and routing.

The frontend can identify the use of a short URL by checking the X-Short-URL header. If the header's value is true, it means the original URL was shortened. This information can be handy when deciding whether to display an introductory element in the UI sa mentioned in #1873.

---

The configuration change:

```conf
set $maproulette "maproulette.org";

location ~ ^/c/(\d+)$ {
    add_header X-Short-URL true;
    return 301 https://$maproulette/browse/challenges/$1;
}

location ~ ^/p/(\d+)$ {
    add_header X-Short-URL true;
    return 301 https://$maproulette/browse/projects/$1;
}

location ~ ^/c/(\d+)/t/(\d+)$ {
    add_header X-Short-URL true;
    return 301 https://$maproulette/challenge/$1/task/$2;
}
```

---

Staging examples of a short url to the expanded url:

- Public Project
  - Short: <https://staging.maproulette.org/p/45411>
  - Full:  <https://staging.maproulette.org/browse/projects/45411>
- Public Virtual Project
  - Short: <https://staging.maproulette.org/p/53274>
  - Full: <https://staging.maproulette.org/browse/projects/53274>
- Public Challenge
  - Short: <https://staging.maproulette.org/c/40274>
  - Full:  <https://staging.maproulette.org/browse/challenges/40274>
- Public Task
  - Short: <https://staging.maproulette.org/c/40274/t/170904002>
  - Full:  <https://staging.maproulette.org/challenge/40274/task/170904002>
  -

Validation can be done using `curl`:

```sh
$ curl -I https://staging.maproulette.org/p/45411
HTTP/2 301 
location: https://staging.maproulette.org/browse/projects/45411
x-short-url: true
```

**Comment by jschwarz2030** [comment]
Rolling into v3.14
