### ISSUE TITLE
buttons misaligned

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette3#226]
<img width="348" alt="screenshot 2018-03-26 14 38 05" src="https://user-images.githubusercontent.com/120452/37932259-40ef2f9e-3105-11e8-884f-b9762c4d6785.png">

this is on staging on safari

**Comment by ryanscherler** [comment]
Hi @mvexel ,

I've tried to replicate this issue on Safari and the alignment looks correct for me. Can you clear cache and try again?

**Comment by mvexel** [comment]
Did just that, problem persists.

**Comment by ryanscherler** [comment]
Hmm - this is an odd one. what version of safari are you running? All of our machines are showing consistent results - tough one to test ;-/

**Comment by mvexel** [comment]
<img width="396" alt="screenshot 2018-03-27 14 55 07" src="https://user-images.githubusercontent.com/120452/37994462-db33f1c4-31ce-11e8-9e05-09d6768bdb74.png">

**Comment by ryanscherler** [comment]
Eek - same exact version as mine. I'll have to dig deeper on this as its odd with differing results.

**Comment by mvexel** [comment]
Here's a full screenshot if it helps.

![screenshot 2018-03-27 15 31 43](https://user-images.githubusercontent.com/120452/37996160-f859c2b0-31d3-11e8-854e-2970540eb34c.png)

**Comment by ryanscherler** [comment]
That is so odd - here is my screenshot with the same version as you and same task / challenge.
![task-2563856](https://user-images.githubusercontent.com/881938/37996317-193a78d8-31cc-11e8-8adf-e6fd932e8cc0.png)

**Comment by mvexel** [comment]
Could it have something to do with scaled display? (my old eyes..)

<img width="780" alt="screenshot 2018-03-27 15 36 21" src="https://user-images.githubusercontent.com/120452/37996366-a406029a-31d4-11e8-8ab6-06df2969bfd1.png">

**Comment by ryanscherler** [comment]
On that note - it seems that the style updates we recently did are not being picked up (various gutters, font sizes etc.) seem behind  / cached on your machine. Is there a more 'hard cache' clear you can do to try and see if the correct / latest styles are picked up?

**Comment by mvexel** [comment]
OK will do.. I use the "Empty Caches" in the Develop menu. What should I use instead?

**Comment by ryanscherler** [comment]
Ohh! You could be on to something with text scaling. I honestly have never used that OS option before.

**Comment by mvexel** [comment]
Doesn't seem to make a difference if I set it to native, except for my eyes starting to hurt.

**Comment by ryanscherler** [comment]
Ugh. ok - I will need to defer to @nrotstan to see whats going on here. Seems odd that we have the same setup and differing results.

**Comment by nrotstan** [comment]
I'm also on Safari 11.0.3 and use display scaling, and it looks correct for me. I will try to see if I can come up with any ideas, though. @mvexel, Safari offers a preference for setting a minimum font size -- are you by chance using that? I noticed that when bumping it way up on my machine it could cause some layout issues.

**Comment by mvexel** [comment]
Nope, tried that as well, no change

**Comment by mvexel** [comment]
Tried today to disable all plugins and extensions. No change.

**Comment by mvexel** [comment]
browsing in private mode also no change (I am really trying everything here...)

**Comment by mvexel** [comment]
Also tried to change Mac OS scrollbar setting to show only when scrolling -- no change
