### ISSUE TITLE
Remove twitter links

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette3#2261]
MapRoulette's twitter account has been deleted. We need to remove all links to it from the MapRoulette website.

**Comment by fredao** [comment]
@mvexel asking for weeklyOSM: who deleted the account? You or x?

**Comment by jnicho02** [comment]
...switching it for Mastodon? @MapRoulette@en.osm.town

**Comment by mvexel** [comment]
Yes @jnicho02 that is our Mastodon account.
Once this one is resolved, the twitter link will be gone from the MapRoulette website as well, and replaced by a link to that account.
