### ISSUE TITLE
Document that task URLs are automatically added to changeset comments when the challenge is discoverable

### ISSUE THREAD

**Issue by osmuser63783** [maproulette/maproulette3#2262]
Please document somewhere for challenge creators that a URL linking to the challenge description and task is automatically added to the changeset comment, but only when the challenge is discoverable. This could for example be documented on the Edit challenge page, right under "Changeset Description".

Please consider adding an option / tickbox for challenge creators to include the short link even when the challenge is non-discoverable.

**Background**

As a challenge creator I always make my challenges non-discoverable at first to test them out before making them visible to others.

While testing mine out, I noticed there was no way to find the challenge / task description when viewing a changeset, so I decided I would add a short URL like I had seen it in changeset comments for other challenges. I then spent a bit of time figuring out how to do that. I tried googling how to do it, but all I found was various issues here on the issue tracker talking about a checkbox to do this or plans to make this happen automatically, and thought I was going crazy because I couldn't find the checkbox and it wasn't happening automatically.

The penny only dropped when I read [this issue comment](https://github.com/maproulette/maproulette3/issues/1823#issuecomment-1353841209) which explains that the link is added automatically, but only when the challenge is discoverable :-) So to save future challenge creators from wading through Github tickets in order to find out how to add the link, please document it somewhere :-)

**Comment by CollinBeczak** [comment]
<img width="953" alt="Screenshot 2024-04-01 at 11 51 13 PM" src="https://github.com/maproulette/maproulette3/assets/88843144/9fd81ee8-037c-4725-acb9-0987ec5f707c">
This will be implemented in [this PR](https://github.com/maproulette/docs/pull/40), let me know if you think anything should be changed.
