### ISSUE TITLE
Set zoom of minimap

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette3#23]
I find that often it would makes more sense to me to have the minimap zoomed in a bit more.

This is probably challenge-specific so it would make sense to make this a challenge setting, and / or a user setting.

For an immediate fix, we can set this to zoom level 8 or so by default

**Comment by nrotstan** [comment]
I've increased the zoom of the inset map (to 7), but also added a small extent map to provide additional geographic context.
<img width="343" alt="zoomed_inset_map" src="https://user-images.githubusercontent.com/445970/35878658-c72c53b4-0b2d-11e8-86d1-026bf9cfb7f1.png">

**Comment by mvexel** [comment]
That is an extremely cool solution.
