### ISSUE TITLE
Add tips for new users and to highlight new features

### ISSUE THREAD

**Issue by nrotstan** [maproulette/maproulette3#230]
Add tips that help introduce MR3 to new users, or that can be used to highlight new features/changes for existing users when they are released.

**Comment by mvexel** [comment]
Revisiting, keeping this one alive. We may be able to cover some of this once we have a blog and incorporate recent posts on the homepage. Other ideas:

* When users first log in, show them a modal with some helpful links and a short introduction / welcome note.
* When users first log in after a new point or major release, show a modal with new feature highlights.
* Have a visual guided walkthrough for new users like iD has.

**Comment by mvexel** [comment]
Checking in on this ticket. I think with the limited resources we have I'd rather focus on the documentation than spend time on this.
