### ISSUE TITLE
Cannot sign in … or sign in not present on challenge page

### ISSUE THREAD

**Issue by tordans** [maproulette/maproulette3#2300]
**Describe the bug**

I am trying to contribute to https://www.maproulette.org/browse/challenges/36475
The page tells me I am not logged in.
When I use the login button, I see an empty page.
When I use the login button that page, I see my dashboard, apperently signed in.
I then go back to the challenge page from above … and I am **not** logged in.

**Video: https://we.tl/t-FCLYGjxOh5** 
This video will be there until 24.03.2024, please download before that…

**Expected behavior**

- When I click login, I get logged In or I see an error message
- When I am logged in already, the page redirects me to where I came from
- I get error messages that guide me to a solution 

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome

**Comment by ljdelight** [comment]
Confirmed, I was able to repro easily and I do not see this with other challenges.

I'm logged in and then visit that challenge URL; the FE request to the whoami route doesn't include the `cookie` header, so it seems a UI code path is not happy with something with that challenge and clears the cookies.

**Comment by tordans** [comment]
> with that challenge

I tried a different add tags challenge with the same Effect. Did not try regular challenges though.

**Comment by ljdelight** [comment]
@tordans this is caused by us moving to oauth2 a few months back. The allowed domains for auth is 'maproulette.org', not the www-prefixed domain, and that's why the session is cleared and why login doesn't work.

We'll get the nginx conf updated to redirect (http 301) the www urls to the main domain. In the meantime, simply remove the 'www' piece from that URL or use the short-link version https://mpr.lt/c/36475

**Comment by ljdelight** [comment]
Okay this should be fixed, I updated the conf to do the below. I used http 301 so that SEO links update, if any exist anyway, update to the main domain without the 'www'.

```
server {
  ...
  # Redirect www.* to the main domain name
  if ($host = 'www.maproulette.org') {
      return 301 https://maproulette.org$request_uri;
  }
}
```

Let me know if it's working as expected 👍

**Comment by tordans** [comment]
Yes, I can sign in now and see the page. Thanks for the fix!
