### ISSUE TITLE
Docs: Update "Quick Fix Challenges" wording, improve linking

### ISSUE THREAD

**Issue by tordans** [maproulette/maproulette3#2306]
On https://learn.maproulette.org/en-us/documentation/quick-fix-challenges/ the wording is still "Quick Fix Challenges" but on https://learn.maproulette.org/en-us/documentation/creating-cooperative-challenges/ I read that this is an old wording.

> ... an alternative Tag Fix (formerly quick fix) style cooperative challenge can be created instead

It's quite confusing to have both names used in the docs.

There are also two small addition request:
- Could the "Creating Tag Fix Challenges" get an id-attribute so it can be used as an anchor (https://learn.maproulette.org/en-us/documentation/creating-cooperative-challenges/)
- Could the end user page (https://learn.maproulette.org/en-us/documentation/quick-fix-challenges/) be linked from the developer page and the other way around so one can understand the meaning of the different pages more easily

**Comment by CollinBeczak** [comment]
This linked text will contain the link anchor to the "create tag fix challenges" section:
link: https://learn.maproulette.org/en-us/documentation/creating-cooperative-challenges/#creating-tag-fix-challenges
<img width="1191" alt="Screenshot 2024-04-01 at 12 33 00 PM" src="https://github.com/maproulette/maproulette3/assets/88843144/047103ed-17a7-4c46-b5d1-1665246a813a">

This link text will redirect to the tag fix challenges page:
link: https://learn.maproulette.org/en-us/documentation/tag-fix-challenges

<img width="1069" alt="Screenshot 2024-04-01 at 12 37 06 PM" src="https://github.com/maproulette/maproulette3/assets/88843144/c381eb9d-7281-473d-b735-c794b8603c73">

**Comment by CollinBeczak** [comment]
There is a looping issue i discovered that you will see if you go to those links before the PR below is deployed.
