### ISSUE TITLE
Add simple control to quickly view sharable link for challenge

### ISSUE THREAD

**Issue by nrotstan** [maproulette/maproulette3#231]
When working on a challenge, it's currently possible to get hold of a share link indirectly through the social sharing controls, but it'd be nice if there was a quick, unobtrusive way to view/copy the link without having to initiate social sharing (perhaps a small chain-link icon next to the challenge name). It should work for both virtual challenges and standard challenges.

**Comment by mvexel** [comment]
We could use #225 :)
