### ISSUE TITLE
New tipe of Completion Status: "Can't complete - fixme tag added"

### ISSUE THREAD

**Issue by mrondr** [maproulette/maproulette3#2341]
**Is your feature request related to a problem? Please describe.**
It happens to me that many times that the current mapping of the area requires further information to be performed
For instance, in the [helipad area challenge](https://maproulette.org/browse/challenges/40681)), it seems that sometimes the location of the helipad is automatically fetched from external sources. This location is completely off or, at the very least, unmatched by satellite image, hence requiring further investigation for the task to be performed.

The current scoring point does not encourage users to spend the time to add a fixme tag to the object, but rather, it encourages to save time and just mark it as can't complete. 

**Describe the solution you'd like**
Awarding 2 points to a "Can't complete fixme tag added" type actions would reward such positive action.

**Describe alternatives you've considered**
Not pertinent.

**Additional context**
Not pertinent.

**Comment by mvexel** [comment]
I understand the issue, but I am hesitant to add more completion options. Having too many choices makes it harder for users to know what to do. I would rather the mapper (you perhaps?) leave a comment on the challenge to encourage the author to improve it. 

There is something to be said for letting the challenge author add flexible / custom completion options, but that requires quite a lot of work and design on our part. For now, unfortunately, I don't see use working on adding new statuses. I do appreciate the feedback!
