### ISSUE TITLE
TagFix Challenge always returns "Oops, your changes could not be saved"

### ISSUE THREAD

**Issue by wielandb** [maproulette/maproulette3#2344]
**Describe the bug**
I have tried to create multiple challenges using the new cooperative "TagFix" type challenge. I generate the GeoJSON using python, and I can upload it and the tasks are built without problems.

However, when trying to commit a change in such a MapRoulette Challenge, it always returns the error "Oops, your changes could not be saved".

What is the problem? And even more important: How do I as challenge owner can get feedback about what's wrong with my challenge?

**Expected behavior**
When "yes" is clicked, the OSM object is updated with the proposed tags.

**To Reproduce**

* Put this in a GeoJSON file:

```
{"type": "FeatureCollection", "features": [{"type": "Feature", "geometry": {"type": "Point", "coordinates": [13.4495432, 48.567051]}, "properties": {"@id": "relation/272138", "latitude": 48.567051, "longitude": 13.4495432}}], "cooperativeWork": {"meta": {"version": 2, "type": 1}, "operations": [{"operationType": "modifyElement", "data": {"id": "relation/272138", "operations": [{"operation": "setTags", "data": {"name": "Wörthstraße"}}]}}]}}
```

* Create a challenge with it
  * Try to click "yes" on the proposed edit
* See error

**Desktop (please complete the following information):**

* OS: any
* Browser any

**Comment by CollinBeczak** [comment]
You were running into this error:
{
    "status": "KO",
    "message": "https://www.openstreetmap.org/api/0.6/changeset/151735202/upload failed with status code 412 (Precondition failed: Way 272138 must have at least one node)"
}
The relation your were trying to submit was being wrapped in a way wrapper instead of a relation wrapper. Thank you for making a ticket about this! I will have a hot fix for this soon.

The fix: https://github.com/maproulette/maproulette-backend/pull/1121

**Comment by wielandb** [comment]
Thank you very much for the fix!

**Comment by wielandb** [comment]
Unsure if this is of interest to improve UX, but on our end, we did not get the "Way 272138 must have at least one node" part of the error, just everything before. We could deduce that it had something to do with the relation not beeing handled correctly by the 412 error, but maybe it would be an idea to relay the error reason to the user to improve future debugging.

**Comment by wielandb** [comment]
Question: When will this fix be in production? So that we can check if this resolved our issue.
