### ISSUE TITLE
Preserve Overpass query when editing Challenge

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette3#236]
When you edit an existing Challenge based on an Overpass query, then save it, go back in and edit it again, the Overpass query is not displayed (or at least not in the case I just looked at, http://maproulette.org/mr3/admin/project/1/challenge/81/edit

**Comment by mvexel** [comment]
In another case http://maproulette.org/mr3/admin/project/1/challenge/222/edit it was in fact preserved.

**Comment by nrotstan** [comment]
PR #214 (in beta.3) makes some changes around how the data sources are managed when editing a challenge, and I think will address this issue. Let's retest once beta.3 is deployed.

**Comment by mvexel** [comment]
I'm thinking it may not be the overpass query, the challenge I mentioned in the initial ticket may have been created using local GeoJSON (upload). In any case, we should make that field less ambiguous when going back in and editing a challenge (see also #253, somewhat related). To discuss, what is the expected behavior if the source is changed after initial creation, or do we even want to allow that? I'm  thinking it would be more straightforward to have the source field be immutable when going back in and editing the challenge.

**Comment by nrotstan** [comment]
It's true that for locally-uploaded GeoJSON, there is no display or information about the data when one goes back to edit the challenge. It'd be nice to at least display the filename of the file that was uploaded during creation (like we do after a fresh upload).

**Comment by nrotstan** [comment]
With PR #285, the source will no longer be modifiable once a challenge has at least one task. This should still allow modification if the tasks all fail to build due to, for example, a bad Overpass query. For challenges populated from a local GeoJSON upload, once the source becomes read-only the dropzone will be replaced with a message indicating that the existing file will be used.
