### ISSUE TITLE
MR does not display tasks in challenges

### ISSUE THREAD

**Issue by DoPol** [maproulette/maproulette3#2376]
**Hi MR team!**

** When testing some tasks on a new MapRoulette challenge today I noticed that when you select a task it starts very zoomed out like shown in the picture, making it hard to see where the edit needs to be done. And when heading to the next task, the map doesn't move, making it basically impossible to know where to map. Also there is no way to move to next tasks.**
![image (2)](https://github.com/maproulette/maproulette3/assets/124360352/d0b59c10-e8a5-4394-a3e2-ce90bbd7add8)
Here's the challenge link we spot it in:
https://maproulette.org/browse/challenges/48694

**To Reproduce behavior all you need to do is challenge opening and start  - you will see task's are displayed hence mappers have no clue where to map or can't select other tasks**

Can you please have a look asap as it stops us from OSM improvements?
thank you in advance 
regards
Domi

**Comment by CollinBeczak** [comment]
I'll get this fixed today, we had a big dependency bump that was impactful for maps that likely led to this issue. Thanks for reporting this bug and please open another issue if you find anything else that looks weird.
