### ISSUE TITLE
Fench translation is gone?

### ISSUE THREAD

**Issue by overflorian** [maproulette/maproulette3#2377]
Hi, trying to fix a minor issue with the french translation, I find that the repository indicates that most of the language is NOT translated : https://app.transifex.com/osmlab/maproulette3/language/fr_FR/
Is it the good repository ? What happen to most of the translation? We've spent hours and hours translating carefully the service, I hope it hasn't been lost. 

Thanks

PS: the website itself is still translated in french, so it's even more confusing to me.

**Comment by CollinBeczak** [comment]
The website uses this: https://app.transifex.com/osmlab/maproulette3/language/fr/ . I don't know all the details about transifex, but could this be what you are looking for? Or are you sure that it is that separate french language?

**Comment by CollinBeczak** [comment]
Im not sure why there are two french folders... @mvexel and @jschwarz2030, either of you know why this happened and how we can prevent duplicate languages if this wasn't intentional?

**Comment by overflorian** [comment]
You are right: I was looking at the wrong page.
I recommand you get rid of the useless and confusing duplicate, regards

**Comment by mvexel** [comment]
@overflorian unfortunately Transifex makes it too easy to request and support multiple "versions" of a language. In some cases this makes sense, when there are significant variations of a single language, enough to warrant a separate entry.
I will remove [the unused one](https://app.transifex.com/osmlab/maproulette3/language/fr_FR/). Thanks for helping out @overflorian !

**Comment by mvexel** [comment]
Deleted.
