### ISSUE TITLE
Improve Tag Fix UX to make it clearer that the mapper is direcly editing OSM

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette3#2405]
Inspired by [this thread](https://community.openstreetmap.org/t/maproulette-critique/116922) on the community forum. 

The Tag Fix mode needs UI improvements, we need to make absolutely sure that the suggested fixes are always visible regardless of any user-defined layout or screen size. There may also be other UI hints we can provide that the action taken by the mapper directly modifies OSM.

This needs discussion before we decide on an implementation path.

**Comment by mvexel** [comment]
Discussed with @jake-low and @CollinBeczak: Let's add the details of the changes to the confirmation modal to ensure the user sees it and is fully aware that they are committing changes to the OSM map even though they have not opened an "editor". I like the idea that came up of having the user scroll (or do some other additional action) before they can confirm. But I'll leave it up to you to decide based on your experience as mappers what the best way is to convey this information.

**Comment by CollinBeczak** [comment]
Thoughts on this design?

Example of modal before proposed change:
![Screenshot 2024-10-28 at 1 50 03 PM](https://github.com/user-attachments/assets/2bfdd892-4029-43f2-98df-805a8a5632f7)

Example of modal after proposed change:
![Screenshot 2024-10-28 at 1 48 04 PM](https://github.com/user-attachments/assets/150d3205-b4cb-47e7-9396-9e54cbd82ae6)
