### ISSUE TITLE
Do not reset map layers on task change.

### ISSUE THREAD

**Issue by homersimpsons** [maproulette/maproulette3#2451]
**Describe the bug**
Map layers are resetted after changing task.

**Expected behavior**
Map layers should not change on task change.

**To Reproduce**
1. Go to a task (example https://maproulette.org/challenge/11605/task/234514862)
2. Click on "layer" icon on the map
3. Select a map feature (example OSM Data > Node)
4. Do the task / complete it
5. (bug) On the new task the selected map features are resetted

**Screenshots**
Selecting layers:
![image](https://github.com/user-attachments/assets/4446bf74-d9b9-4747-8b51-72d3f7bed93f)

On task complete the view becomes
![image](https://github.com/user-attachments/assets/e0397f4d-c0f0-4ab8-8806-35cd289ab406)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox
 - Version: 130.0.1

**Additional context**
I did not test for variations of this bug. Also it may not be desirable to keep layers when changing challenge. But for some challenge having the node data helps quickly diagnose whether something is already fixed or not.

**Comment by homersimpsons** [comment]
I do not know if this is supposed to be live. But I just tested it and it still resets the layer on task change (when completing it).

**Comment by CollinBeczak** [comment]
Sorry, its not live yet. But the fix will be included in our next deployment. I will reopen this ticket until then.

**Comment by CollinBeczak** [comment]
This should be fixed now in production, please let us know if there are any other issues with the map and if your issue is resolved.

**Comment by homersimpsons** [comment]
I confirm it works, thank you!
