### ISSUE TITLE
Leaderboard and for editing in JOSM “Forwarding” bug

### ISSUE THREAD

**Issue by vogelfreier** [maproulette/maproulette3#2471]
Whether under Windows 11 or under one of the Linux software, after logging in to the Firefox browser as a user “vogelfreier”, I am shown the statement in the dashboard that I am in 52nd place and according to the worldwide list I am then in 555th place since October 21, 24.
When selecting a challenge, then selecting a node, the bubble pops up with info and when “Start task” is clicked, the raw data is not downloaded in JOSM in version 19320, remote control switched on. (Editing in ID or Rapid is not an option for me).
Greetings
translated from German with deepl.com

**Comment by mvexel** [comment]
Hello @vogelfreier 
When you click on "Start Task" you should see the MapRoulette Task page, which would look something like this:
<img width="1078" alt="image" src="https://github.com/user-attachments/assets/8516aec9-11bb-4649-aca0-5f9556987852">
You can then use the dropdown menu to select "Edit in JOSM":
<img width="255" alt="image" src="https://github.com/user-attachments/assets/b6dc35da-3774-4d52-b635-c5bd98606231">
With the button now showing "Edit in JOSM" you can click it and JOSM should open and load the data using remote control:
<img width="278" alt="image" src="https://github.com/user-attachments/assets/cddfc24c-6727-441e-94d5-4a8479fa132c">
Let me know if this is what you were looking for and if this resolves your question.

**Comment by vogelfreier** [comment]
Hello,
I can now play maproulette again.
But how should I try to rewrite it, when I started any task, I could not get any data into the JOSM (although the remote control is activated) despite clicking on the button of JOSM, no matter under Windows 11 or one of the Linux applications like Debian. A change in ID-Editor went and was able to edit this, but since the requirement for a clear view of things should be given to see only the aerial view, it is not done with the ID-Editor.
It seemed to me that the facelifting I had done slowed me down.
With some delay, thanks for asking.

Translated with DeepL.com (free version)
