### ISSUE TITLE
Allow global challenges

### ISSUE THREAD

**Issue by Noki** [maproulette/maproulette3#251]
I would love to see a way to create a global challenges eg. for phone number and fax number formatting.
It should be possible to set an interval to refresh the data so it automatically updates to find new tasks and delete tasks that were already fixed. When I worked with the Overpass API I devided the world into smaller tiles and did a lot of requests with small bounding boxes to get this kind of data on a global scale. A global challenge should automatically do that in the build process and ignore a bounding box specified by the user. Global challenges should be flagged so a user could hide them.

**Comment by mvexel** [comment]
Thanks for the suggestion @Noki. We discussed this in an OSM message thread earlier. I think the idea makes sense. MapRoulette was originally designed for 'local' use cases, but could be really useful for larger scale cleanup tasks too. The phone number challenges he set up are an example of this.

**Comment by nrotstan** [comment]
Based on discussion from #430, also support rebuilding of global challenges once supported.

**Comment by matkoniecz** [comment]
Seems covered by "Continuous Challenges" in #1910
