### ISSUE TITLE
Add a leaderboard 

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette3#254]
We discussed this previously but I don't think we created a ticket for it. 

It would be really fun and an great motivator to add leaderboards to MapRoulette. Which users are solving the most tasks, overall and perhaps also per challenge.

This could be a new top level menu item.

**Comment by mvexel** [comment]
Also there is this: http://www.missingmaps.org/leaderboards/#/maproulette

**Comment by adiatmad** [comment]
How could I found for accounts not on entire list? Thank you.

**Comment by mvexel** [comment]
@adiatmad what do you want to find? Perhaps we can consider adding it.

**Comment by adiatmad** [comment]
Hi @mvexel, I find for these accounts

adam maulana, aglisdwininta, Akrimullah, alifatri, anisa berliana,
atmahadi, DaryR, dennisramadhan, DiahW, Dianaww, Elisabeth S, Hajid Naufal,
Hanif Arafah Mustofa, ikopanjirukmana, Ilmananude, irwan hidayatullah,
MutyAfadila, Riyadi Wibowo, silviasdw, Yeni Primasari, Zainab Ramadhanis

Thank you for consider adding it.

Pada tanggal Min, 15 Apr 2018 03.25, Martijn van Exel <
notifications@github.com> menulis:

**Comment by mvexel** [comment]
Ah, you want stats for individual users. What information are you looking for? Just how many tasks solved? For what time period (day, or week, or month, all time)?

**Comment by adiatmad** [comment]
Yes I want to know how many tasks solved by each account for all time. Thank you.

**Comment by nrotstan** [comment]
PR #318 adds a global leaderboard.
