### ISSUE TITLE
Allow Overpass Turbo features in Overpass query

### ISSUE THREAD

**Issue by rmikke** [maproulette/maproulette3#256]
Overpass query:
```
[out:json][timeout:900];
(
{{geocodeArea:"Polska"}};
)->.myArea;
(
  node["amenity"="pharmacy"][!"opening_hours"](area.myArea);
  way["amenity"="pharmacy"][!"opening_hours"](area.myArea);
  relation["amenity"="pharmacy"][!"opening_hours"](area.myArea);
);
out center;
```
returns:
![Error message](http://cdn.blabler.pl/image/24Im)

**Comment by mvexel** [comment]
`{{geocodeArea}}` is an Overpass Turbo feature, I believe. Can you try with [this query](http://overpass-turbo.eu/s/xs4)?

**Comment by mvexel** [comment]
I didn't know that Turbo features could be used outside of Turbo! @mmd-osm @tyrasd can you shed light on how that works?

We'll look into it. Thanks for changing the title for me :)

**Comment by mmd-osm** [comment]
You could use Export —> query —> copy standalone query, which automatically replaces those moustache tags for you.

Josm has reimplemented the same logic in Java, afaik. Otherwise {{}} Syntax is not something Overpass API understands on its own.

**Comment by mmd-osm** [comment]
Ah that was the french spelling... should be like in here http://mustache.github.io/

**Comment by mvexel** [comment]
So we could improve the instructions on the relevant Challenge wizard page to say that if you're using Overpass Turbo:

1. Prepare and test query in [Overpass Turbo](http://overpass-turbo.eu/#)
2. Use Export --> Query --> Standalone --> Copy as standalone query (this does not seem to work in Safari)
3. Copy the query into the text box below.

On top of that we could add some simple regex detection `\{{2}[^\}]+\}{2}` and trigger a notice when folks try to submit a query with moustache tags. What do you think, would that work as a solution, @rmikke ?

**Comment by mvexel** [comment]
@mmd-osm no no I wasn't making fun of the spelling, I just thought it was a really funny name for these types of placeholder tags!

**Comment by rmikke** [comment]
It would be better to accept Overpass Turbo syntax, especially if exporting standalone query not always works (the Safari case) but if it's not possible or too hard, then yes, instruction and detection is acceptable solution, as it tells the user what to do.

**Comment by mmd-osm** [comment]
> Overpass Turbo syntax, especially if exporting standalone query not always works (the Safari case) 

_Copy as standalone query_ requires access to the clipboard. If that doesn't work for whatever reason, there's still _Download as standalone query_.

Here's a [link](https://josm.openstreetmap.de/browser/josm/trunk/src/org/openstreetmap/josm/io/OverpassDownloadReader.java?rev=12596) to the respective JOSM implementation. `{{geocodeArea}}` also depends on additional Nominatim queries.

**Comment by rmikke** [comment]
As long as the user gets clear instructions, it's OK with me.

**Comment by nrotstan** [comment]
With PR #289, an informative error message will be displayed if Overpass Turbo query shortcuts are used. It'll be in the beta.5 release.
