### ISSUE TITLE
Make a download button for admins

### ISSUE THREAD

**Issue by joostschouppe** [maproulette/maproulette3#261]
I might have missed the button, but for the people who don't have experience working with API's, it might be handy to just be able to download the entire challenge with all the current task status.

**Comment by nrotstan** [comment]
Thanks for the suggestion, Joost. Do you think a CSV export like #124 would be sufficient, or are you thinking something else?

**Comment by joostschouppe** [comment]
Sorry, didn't notice that one. Yes, that's exactly what I had in mind; Martijn also mentions GeoJSON there, having both would be excellent.

**Comment by mvexel** [comment]
Excellent, closing this as a duplicate then. See you at #124 :)
