### ISSUE TITLE
Don't offer already-complete challenges in results to signed-out users

### ISSUE THREAD

**Issue by picsi** [maproulette/maproulette3#283]
One of the tasks suggested in my region was PlaneMad's Wikidata for capital cities which is already over. It would be useful to have something in the UI to show users it's not available anymore. Maybe grey it out, or put a notice, or even remove from the viewable catalog.

**Comment by nrotstan** [comment]
Thanks for the report, picsi. Can you tell me if this is still happening for you? I think it may be fixed now. If not, can you provide the full name of the challenge you're seeing? It's definitely a bug if you're being presented with challenges that are already complete. Thanks!

**Comment by mvexel** [comment]
Or @picsi do you mean the opposite -- someone tells you about a Challenge / gives you the link and you want to be able to find it in MapRoulette, but clearly marked as 'Over' / 'All Done'?

**Comment by nrotstan** [comment]
Thanks for the help, @picsi. I can reproduce this with a clean session that is not signed in. As a temporary work-around, signing in should cause those completed challenges to disappear.
