### ISSUE TITLE
When editing a task, setting status from 'Not an Issue' to 'Created' gives an error

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette3#3]
<img width="546" alt="screenshot 2018-01-22 14 17 25" src="https://user-images.githubusercontent.com/120452/35244997-5a1f15e0-ff7f-11e7-8e01-bd67459dd33b.png">

**Comment by nrotstan** [comment]
I just realized this issue is regarding editing a task as a challenge owner, not completing it as an end user. Removing the "fixed in develop" label.

**Comment by nrotstan** [comment]
Addressed for real now ;-)
