### ISSUE TITLE
action button alignment 

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette3#39]
The action buttons are all in one single column leaving white space in the left sidebar:

<img width="374" alt="screenshot 2018-02-02 13 01 41" src="https://user-images.githubusercontent.com/120452/35752539-938f433e-0819-11e8-972e-83dd695f9cc9.png">

How about we have the FIX button take up one row full width (and stand out with bolder color or so) and the others next to each other in one row below it? Arguably the FIX button is the most important one and should be the most obvious action to take, visually

**Comment by nrotstan** [comment]
That single-column layout with all the extra whitespace was definitely a bug. It's been fixed in develop. That said, we can still discuss what an ideal layout might look like.
