### ISSUE TITLE
Leave off badge when no messages

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette3#53]
A red badge draws a lot of visual attention, we should leave it out when there are no messages, as seen here:

<img width="49" alt="screenshot 2018-02-05 10 45 39" src="https://user-images.githubusercontent.com/120452/35820063-d8880300-0a61-11e8-8a1d-42b889f71205.png">

**Comment by nrotstan** [comment]
I didn't remove the badge altogether, as I think it's nice to be able to see at a glance that there are zero comments (especially when the sidebar is minimized when working on tasks), but the badge is now rendered in a light grey color when there are no comments so as to be less visually distracting.

**Comment by mvexel** [comment]
That makes sense to me. Thanks!
