### ISSUE TITLE
When expanding challenge, 'unable to fetch task clusters'

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette3#58]
When expanding a challenge in the list, it shows the bounding box but then pops up an error 'unable to fetch task clusters'. The challenge does have (open) tasks.

Happens when expanding challenge id 429, "Add Platforms To Passenger Rail Stations" on the dev instance.

**Comment by mvexel** [comment]
Here's another one that fails, on production: `http://maproulette.org/api/v2/challenge/clustered/2861`

**Comment by nrotstan** [comment]
This should now be fixed with PR maproulette/maproulette2#397.
