### ISSUE TITLE
Tasks on Null Island

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette3#6]
When creating a new challenge, the tasks are loaded correctly, but when you start working on the challenge, the minimap shows the task location on Null Island. Null Island is very pretty but it's not where the tasks are :)

**Comment by mvexel** [comment]
Example task: http://maproulette.eastslopestud.io/mr3/challenge/2828/task/3774219

**Comment by nrotstan** [comment]
Thanks, which challenge (or task) were you looking at?

**Comment by mvexel** [comment]
I'll let you know when I can reproduce. I forgot to copy a link. But it happened with a new challenge I had just created.

**Comment by mvexel** [comment]
Here's one

http://maproulette.eastslopestud.io/mr3/challenge/2832/task/3779257
