### ISSUE TITLE
Make it clearer that filters are active

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette3#61]
I filed #60 just now as I was thinking about this larger issue. I've come back in to MR3 after being away for a bit and finding myself unable to find a challenge that I know exists. Only to realize some moments later that I have filters enabled. I wonder if there is a subtle but effective way to indicate that filters are currently active?

Perhaps underneath the title 'Challenges' in the left bar, show something like `X out of Y shown` combined with some visual emphasis on selected / entered filters?

**Comment by nrotstan** [comment]
With PR #94 , a Clear Filters control will show up next to the Challenges header whenever filters are active. Do you think that's a sufficient visual cue?

**Comment by mvexel** [comment]
Yes, that is definitely good enough.
