### ISSUE TITLE
When editing an existing challenge, give option to replace existing tasks

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette3#7]
When uploading a new JSON file, a new JSON link, or a new overpass query, there should be an option to replace the existing tasks.

**Comment by nrotstan** [comment]
We no longer allow updates to source data once a challenge has tasks. Challenges using Overpass queries can be rebuilt via the Rebuild control.

**Comment by nrotstan** [comment]
I shouldn't have closed this yet. My above statement will be true in beta.5

**Comment by nrotstan** [comment]
Closing now that beta.5 has been released.
