### ISSUE TITLE
Possible option to restrict Challenge access to specific users

### ISSUE THREAD

**Issue by samuelestabrook** [maproulette/maproulette3#74]
This is more a feature request- we are wondering if there is interest in feature that allows only specific OSM users to access or work on a given Challenge.

**Comment by mvexel** [comment]
Hi @samuelestabrook -- thanks for taking the time to submit your feedback and ideas. Much appreciated!

We haven't considered this yet. For now, I think a good workaround is to keep the challenge hidden and share the Challenge URL with select people so they can work on it. 'Hidden' challenges are still accessible, they just don't show up in the list.

Would that work for your use case or do you have something else in mind?

**Comment by samuelestabrook** [comment]
That makes perfect sense. The 'Hidden' option works well for this, thank you!
