### ISSUE TITLE
Feedback upon successful submission of a task

### ISSUE THREAD

**Issue by samuelestabrook** [maproulette/maproulette3#75]
Possible feature request- when a task is successfully handled (marked as Fixed, Skip, Save, Not an Issue) MapRoulette immediately provides the user with the next task. When I initially submitted the task it was unclear to me whether it successfully saved the status of the fix. Maybe some visual feedback for the user could ensure they understand the next task is now loaded? Like some small text that prints into the window that confirms the commit for the user, or something.

**Comment by mvexel** [comment]
This does exist in the current MapRoulette and I think it makes sense to carry it over.

**Comment by nrotstan** [comment]
An animated transition  of the task map is now included that should make it clearer that a new task has been loaded.

**Comment by mvexel** [comment]
GIF or it didn't happen @nrotstan 😄
