### ISSUE TITLE
Bing only loads up to zoom 16, OpenCycleMap missing the API key

### ISSUE THREAD

**Issue by samuelestabrook** [maproulette/maproulette3#76]
Bing imagery loads up to zoom 16, with 17, 18, and 19 having a "Map data not yet available" error.
The OpenCycleMap loads but had an "API Key Required" warning printed on the map.

**Comment by mvexel** [comment]
This would depend on the area. In some regions, Bing imagery reaches Z19. I think it's up to the challenge owner to set a reasonable initial zoom level.

We should probably just remove the OpenCycleMap option. I don't see a super common use case for showing that layer by default, and if folks want to have it, they can supply it as custom URL with their own key.
