### ISSUE TITLE
Possible "Not enough information" option for tasks

### ISSUE THREAD

**Issue by samuelestabrook** [maproulette/maproulette3#77]
In addition to the "Fix," "Save," "Not an issue," and "Skip," another possible option that could help the Challenge creator could be a "Not enough information" option.

**Comment by mvexel** [comment]
Currently we assume that folks try and fix the issue first and then select 'Too difficult / couldn't see'. To me that makes sense as a workflow, but I'd be curious to hear more about a use case where you'd want to see this option appear right away.

**Comment by mgcuthbert** [comment]
I would also add, that generally if the user believes there is not enough information for a given task, then the 'Too difficult / couldn't see' option should be selected along with a comment on the task explaining what information is missing. If it is the challenge itself that in general doesn't have enough information then the user should message the challenge owner.

**Comment by samuelestabrook** [comment]
This makes perfect sense, thank you! "Too difficult / couldn't see" captures this well
