### ISSUE TITLE
Select object in iD upon launch of iD

### ISSUE THREAD

**Issue by samuelestabrook** [maproulette/maproulette3#78]
While working on the  international formatting phone numbers task, we found that the POIs are not selected in iD when launching the editor to check the tags. This required the user to go find the POI among many - maybe a pre-selected POI could help direct the user's attention more precisely.

**Comment by mvexel** [comment]
Yep, and this is supported, but the Challenge provider needs to include the OSM object identifier as a property for each feature in the GeoJSON tasks file. If they don't, we have no way of knowing which thing to pre-select. This comes down to better educating the challenge owners. I'll close this for now, feel free to re-open if you have additional comments on this.
