### ISSUE TITLE
Make parent Challenge accessible from individual task

### ISSUE THREAD

**Issue by samuelestabrook** [maproulette/maproulette3#79]
Possible feature request- when in the task-specific page (e.g. http://maproulette.org/mr3/challenge/2870/task/4261512) there isn't a link to get back to the parent Challenge, requiring navigation through the top menu links. So if a project is not visible, navigating to the parent Challenge requires clicking "Create" and then clicking the specific Challenge, which is not clear to newer users.

**Comment by mvexel** [comment]
What would you like it to link to?

**Comment by nrotstan** [comment]
The challenge name on a task will now link back to browsing the challenge (PR #89)
