### ISSUE TITLE
tasks not serverd random?

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette3#82]
Going through one of my own challenges, I seem to be getting an uncommonly large amount of tasks that are very close to each other. This is in a large (7500 tasks) challenge, so enough tasks that this makes me question the randomness.

**Comment by nrotstan** [comment]
Once the initial task is loaded, additional tasks are served by proximity.

**Comment by mvexel** [comment]
Oh I see! We probably discussed this and I just forgotten about deciding on this behavior. Let’s note to make this a user setting at some point, some really like the random behavior.
