### ISSUE TITLE
Feature request: Mapillary layer on by default as a challenge option

### ISSUE THREAD

**Issue by cbeddow** [maproulette/maproulette3#844]
Some challenges may be Mapillary specific, or another overlay, so in this case it would be nice to check a box to have that overlay be already on when a user visits the challenge for the first time. Currently the user must manually activate that overlay.

**Comment by mvexel** [comment]
Makes sense to add this as an option. Perhaps extend this to any available overlays.

<img width="960" alt="image" src="https://user-images.githubusercontent.com/120452/169088907-6d34badf-8f4c-4570-94eb-ae20fc394464.png">

**Comment by danieldegroot2** [comment]
Related: #865
