### ISSUE TITLE
background layer options - make selections persistent throughout session 

### ISSUE THREAD

**Issue by govvin** [maproulette/maproulette3#865]
![image](https://user-images.githubusercontent.com/5821688/63664983-d70a3580-c7fb-11e9-9db8-6a011ff25250.png)

It's already possible to change how the task is visualized by a contributor,  changing background imagery, for example, or making OSM data visible. 

There seems to be a bug, or maybe I misunderstand the settings, how to keep OSM data visible when I work on a task.  Right now, I need to keep re-enabling OSM data from the background options every time I am assigned a new task, when I already enabled that previously.

**Comment by nrotstan** [comment]
Sorry this didn't get a response earlier, @govvin . We do this to reduce load on OSM, only pulling in data when requested by the mapper. Most of the other imagery/layer settings should stick throughout a given challenge.

How burdensome are you finding this for OSM data?

**Comment by govvin** [comment]
Thank you for explaining the background, Neil. 

It's probably not a deal breaker for most people, but the few, more enthusiastic contributors may find a persistent setting more  convenient. I would, in projects I contribute to.

**Comment by danieldegroot2** [comment]
@mvexel Could you add the [`enhancement`](https://github.com/osmlab/maproulette3/labels/enhancement) and or [`nice-to-have`](https://github.com/osmlab/maproulette3/labels/nice-to-have) labels, please? This will make it easier to find the issue.
