### ISSUE TITLE
In Quick Fix challenges, add option to open issue in JOSM

### ISSUE THREAD

**Issue by nathan-206** [maproulette/maproulette3#920]
If we could get an extra button to open up the feature in JOSM (I know this might be somewhat defeating the purpose of the quick fixes, but), the reason for this is 2 part:
1.	A few times imagery was not clear (in any of them) and I wanted to double check OSC or Mappilary, and the easiest way to do both is within josm, so a nice easy way to get there would be great
2.	A few times I needed to make an additional edit (the business node was not on the building), so again a nice easy way to open up JOSM and make the edit would be great

**Comment by mvexel** [comment]
To address this, let's add an 'open in editor' option in the 'other...' dropdown in the completion buttons. To ensure the right editor is opened, we will need to resurface the editor preference dropdown as well.

Let's also add a shortcut key to open the map area in the preferred editor.
