### ISSUE TITLE
Feature Request. Support user-friendly task identifier in search result markers.

### ISSUE THREAD

**Issue by govvin** [maproulette/maproulette3#951]
Search results will usually look like these:

![image](https://user-images.githubusercontent.com/5821688/67135478-bc2cce00-f24c-11e9-8d51-d7fdbadbf0d2.png)

Clicking on a marker will display the name of the challenge, and the option to start a particular task.

If, for example, a user is looking for a particular task, they have to click on the start link to find out  what that task is about.

Please consider adding the ability to specify an attribute, for example the `{{name}}`` , if that is defined so instead of just a "Start Challenge" a user can click on say,  "Work on {{name}} task".

Some of our contributors, for example, would like to add features that are familiar to them, and would attempt to look for particular tasks.  Right now, it's hit or miss, where they have to click on search result markers to find what they might be interested to work on, go back to search results if it's not what they wanted  and check the next one until they find what they're after.

**Comment by nrotstan** [comment]
Please see https://github.com/osmlab/maproulette3/issues/952#issuecomment-545524887 for a basic proposal on supporting a display name.

**Comment by mvexel** [comment]
I think this is fully supported in the back-end (see linked ticket), it would just need support in the front-end by changing how the popup text is defined.

I was never very happy with the "Start Challenge" wording, this is confusing because what you're really doing is working on this specific tag.

Perhaps we can define a specific external identifier (for example `taskName`, to be determined) that would be used to compose this line. It would then be "Work on {{taskName}}". If `taskName` is not present in the data, "Work on this task" would be the fallback static text.

Open for discussion.

**Comment by CollinBeczak** [comment]
There are a few options we can move forward with to resolve this issue:
use the existing highway property. Example: highway: "bus_stop". Usage: "Work on bus_stop task"
use the existing name property property. Example: name: "11th Ave / I St (WB)". Usage: "Work on 11th Ave / I St (WB) task"
or we can stick with the version i made in the PR above using the task ID.  Usage: "Start task 1842"

**Comment by mvexel** [comment]
Thanks for thinking about this older but still relevant ticket, @CollinBeczak 

The issue I see with solution 1 and 2 is that not every challenge is linked to a specific OSM ID or tag, so information like this would not be available in many cases. But displaying a link to the OSM ID when it exists may be a good compromise.

The task ID itself is not that meaningful to the end user in many cases.

Looking at #952, I am leaning towards having the user identify a "display name" property when creating the challenge, and use that where it's needed, like here. They would set this when creating the challenge. For example, if the task looks like this:

```
{
  "type": "Feature",
  "properties": {
    "id": "43062222-772d-4e49-ac1e-2c66ad3d7dbc",
    "externalId": 1,
    "building": "yes",
    "name": "Some Building",
  },
  "geometry": {
... rest of JSON ...
```

they could identify the `name` property as the display name and we'd use that. 

This would require adding an option to the challenge creation flow, and perhaps modification to the API?

@jschwarz2030 @AndrewPhilbin would like your input here.

Apologies if this was already discussed and decided on.
