### ISSUE TITLE
Location Filter Broken

### ISSUE THREAD

**Issue by jharpster** [maproulette/maproulette3#97]
The location filter for searching for map challenges does not appear to work correctly.  Searching Within Map Bounds appears to have no affect.

**Comment by mvexel** [comment]
Thanks for taking the time to report and trying the new MapRoulette!

Do you have a specific example of a challenge that you think should have been filtered out based on your map extent, but wasn't?

Some background: the filter should work, but perhaps not exactly as you expect it to. It uses a bounding box for each challenge. If a challenge has tasks all over the globe, it would pretty much always show up in the list, regardless of your map extent. More generally, a challenge does not necessarily need to have tasks within the current map bounds to pass the 'within map bounds' filter.

Related: #88

**Comment by mvexel** [comment]
@jharpster this has undergone various improvements since you filed this, and I am pretty confident that the function behaves as expected, and that I can close this. If you still encounter issues, feel free to re-open.
